### ISSUE TITLE
Make logs more grepable

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/sdk#1008]
## Overview

Right now we have automatic trace logs for network services and registries.
They have some annoying issues:
1. They use `info` level
2. Different requests are interleaved.

These issues make it difficult to read the logs. It's next to impossible to tell what is going on when there are even mere dozens of requests.

## Solution

1. Obviously, we need to change the level for trace logs.
The obvious choice would be `trace`. However, our "trace" logs are actually not so detailed. If we were to add a lot of logs inside some chain elements, then we would probably want to be able to distinguish out current trace logs from them, so maybe it would be better to log them at `debug` level.
2. We can add request ID into logger fields, so interleaving lines of logs can be distinguished by IDs.
We would still have issues with multiline logs, since they only have logger fields in their first line.
Most of our log entries are single lines, and the vast majority of multiline entries are stack traces from errors, so this is not a big problem.

The size increase due to adding ID to each line is minor, in comparison to our current logs size. However, we would be able to use, for example, `grep 9763b41a-2ff6-40e3-8475-7d9dae986f13`, to reduce the big log file to only the important part.

## Implementation

1. The log level for traces is set here:
https://github.com/networkservicemesh/sdk/blob/d4734b5c8e81c4d608572f5db3111b6903bd9877/pkg/tools/log/logruslogger/logruslogger.go#L217
2. We can add field into the context here, using `log.WithFields` (same for other trace elements):
https://github.com/networkservicemesh/sdk/blob/d4734b5c8e81c4d608572f5db3111b6903bd9877/pkg/networkservice/core/trace/server.go#L75

**Comment by d-uzlov** [comment]
I have actually already implemented it locally for debugging of heal issues found during scalability testing. It helps a lot.

**Comment by denis-tingaikin** [comment]
@d-uzlov Be free to open PR!

**Comment by edwarnicke** [comment]
>Obviously, we need to change the level for trace logs.
The obvious choice would be trace. However, our "trace" logs are actually not so detailed. If we were to add a lot of logs inside some chain elements, then we would probably want to be able to distinguish out current trace logs from them, so maybe it would be better to log them at debug level.

As a side note, in the sdk-vpp code, I do my internal logs at `debug` level.  That isn't a commentary on what they *should* be ... just what they are.  It can be changed if need be.

**Comment by edwarnicke** [comment]
> We can add request ID into logger fields, so interleaving lines of logs can be distinguished by IDs.
We would still have issues with multiline logs, since they only have logger fields in their first line.
Most of our log entries are single lines, and the vast majority of multiline entries are stack traces from errors, so this is not a big problem.

I like this idea very much... but there's one practical corner case... what do we do in the case where we haven't got a Connection ID yet?  I suspect this is quite solvable... but will need to be solved :)

**Comment by d-uzlov** [comment]
> I like this idea very much... but there's one practical corner case... what do we do in the case where we haven't got a Connection ID yet? I suspect this is quite solvable... but will need to be solved :)

When I was doing my testing, I was getting connection ID in 2 ways:
1. When I know that something went wrong on a certain pod, I can search for the pod name and find connection path information containing this pod. The easiest place for it would actually be the diff of the first request, where we change connection path, and that change is logged.
2. When there is an error in the logs, the error line contains connection id, and then I can use grep to see the full history of what happened with the related connection.

**Comment by denis-tingaikin** [comment]
PR https://github.com/networkservicemesh/sdk/pull/1012 is not looking great for us and we want to consider a list of improvements for logs in term of the issue.

**Comment by denis-tingaikin** [comment]
@edwarnicke  Finally, all PRs are merged!

@Mixaster995 Thanks!
