### ISSUE TITLE
Add `closer` server to the NSMgr chain

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#1032]
## Issue
Client performs `Close` with some context timeout. It can be enough to reach NSMgr but in some cases (e.g. on high load) it can be not enough to pass the whole networkservice chain across all hops, so this `Close` would fail even it has reach the NSMgr.

## Solution
Add `closer` server in the beginning of the NSMgr networkservice chain, so it would restart `Close` event on NSMgr application context with the bigger timeout.

## References
https://github.com/networkservicemesh/sdk/issues/1031

**Comment by edwarnicke** [comment]
@Bolodya1997 Isn't this already taken care of by the Refresh timer?

**Comment by Bolodya1997** [comment]
I guess this should be resolved by https://github.com/networkservicemesh/deployments-k8s/issues/906, so we can close this issue.
