### ISSUE TITLE
Registry returns incorrect result

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#1048]
## Current Behavior

Registry can return incorrect result, if we already registered network service with the same name but with a different payload.

## Failure Information (for bugs)
Let's take a look at `TestMemif2Wireguard2Kernel` logs. 
We need to use IP payload instead of ETHERNET.

[TestRunBasicSuite.zip](https://github.com/networkservicemesh/sdk/files/6907643/TestRunBasicSuite.zip)

## Steps to Reproduce

Apparently, we have the next steps in this test:
1. **[Test A]**: Run test
2. **[Test A]**: Register NS: `{"name":"icmp-responder","payload":"ETHERNET"}`
3. **[Test A]:** Run ping and finish test
4. **[Test B]**: Run test
5. **[Test B]**: Register NS: `{"name":"icmp-responder","payload":"IP"}`
6. **[Test B]**: NS from previous test with wrong payload is used
7. **[Test B]**: Ping works fine, because we use VxLAN mechanism instead of Wireguard

**Comment by edwarnicke** [comment]
Good catch!
