### ISSUE TITLE
Registry heal works incorrect if NSMgr changes IP address after restart

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#1079]
## Expected Behavior
After NSMgr restart all related Endpoints should reconnect and update registrations in a short time.

## Current Behavior
After NSMgr restart it sometimes changes IP address:
1. Endpoint sends registration request to NSMgr with the old name.
2. NSMgr sends registration request to Registry with the old name and a new URL.
3. Registry returns an "already registered" error.
4. 1-3 repeats until old registration expires (1 minute by default) - during this time all NSMgr Endpoints are not accessible from other NSMgr because Registry still holds old NSMgr URL.
5. Registry updates registration.

## Steps to Reproduce
1. Run https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/heal/remote-nsmgr-restart.

## Failure Logs
[nse-kernel-849cd6b9d7-xxvxh.log](https://github.com/networkservicemesh/sdk/files/7154332/nse-kernel-849cd6b9d7-xxvxh.log)

## Solution

1. Delete `setid`.
2. Delete `checkid`.
3. Update tests for sdk.

**Comment by edwarnicke** [comment]
@denis-tingaikin What are your thougths on simplifying setid for use in non-K8s systems?

**Comment by denis-tingaikin** [comment]
@edwarnicke basically we can only to append UUID for the outgoing nse.Name on the client-side. Currently, we have something similar but it is a bit complicated. See at 
https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/setid/client.go#L46-L65

**Comment by denis-tingaikin** [comment]
```go
func (c *setIDClient) Register(ctx context.Context, nse *registry.NetworkServiceEndpoint, opts ...grpc.CallOption) (reg *registry.NetworkServiceEndpoint, err error) {
     if  _, ok := metadata.Map(ctx, true).Load(nse.Name); !ok {
         nse.Name = nse.Name + uuid.New().String()
         metadata.Map(ctx, true).LoadOrStore(nse.Name, struct{}{});
     }
     next.NetworkServiceEndpointServer(ctx).Register(ctx, nse)
}
```

**Comment by edwarnicke** [comment]
So the question is, why are we changing the names from what were provided?

**Comment by denis-tingaikin** [comment]
> So the question is, why are we changing the names from what were provided?

For k8s resources have unique names.

For non-k8s systems we can have non-unqie names.

What if we have two or more registry clients from non-k8s system that registers the endpoint with the same name?

So to avoid problems with we can simply use UUIDs based on rfc 4122 on these clients.

**Comment by denis-tingaikin** [comment]
Another option that we can use it is:

add field `registration_time` for nses.

It also will solve https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/3 :)

**Comment by edwarnicke** [comment]
I feel like the eventual solution to this is Spiffe Ids ... 

Do we need to solve this for 1.1, or could we solve it for 1.2?

**Comment by denis-tingaikin** [comment]
I think yes it can affect heal/upgrate use-cases 
https://github.com/networkservicemesh/cmd-nse-icmp-responder/issues/287

**Comment by denis-tingaikin** [comment]
So we can start with UUIDs because it simply and consider to rework it in 1.2 with spiffe ids

**Comment by edwarnicke** [comment]
I wasn't suggesting we start with uuids... I was suggesting we simply stop overriding the NSE name entirely in the registry, have the NSEs register with their Pod names, and come back to it in 1.2.

**Comment by denis-tingaikin** [comment]
@edwarnicke OK, sound good

**Comment by denis-tingaikin** [comment]
Added solution section.

@edwarnicke Do you agree with the solution?

**Comment by edwarnicke** [comment]
@denis-tingaikin Its a matter of who names the thing: the NSE registering or the Registry.  If its the NSE, we shouldn't be salting them with uuids.

If we want to be able to have a thing restart and show up as the same registration, the name needs to come from the NSE.

I'm quite open to talking about the fundamentals of this problem... but those fundamentals are around what entity names the NSE and the implications of that for registry healing, etc.

**Comment by denis-tingaikin** [comment]
> If we want to be able to have a thing restart and show up as the same registration, the name needs to come from the NSE.

Registry server sets expire time, so even if nse has restarted then old nse registration will be deleted by expiration time.

**Comment by edwarnicke** [comment]
> Registry server sets expire time, so even if nse has restarted then old nse registration will be deleted by expiration time.

Its not about the expiretime and who sets that... if I am an NSE, I can figure out my name through some means that is deterministic for me, register it, and upon restart, determine the same name for myself, and re-register.

The real key question is: how does a restarting NSE figure out its own name?

One other side question... do the NSEs currently in the system remove their registration as part of normal shutdown for them?

**Comment by denis-tingaikin** [comment]
@edwarnicke 
All PRs are merged. So closing.
