### ISSUE TITLE
`authorize` is very slow on long path

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#1095]
## Expected Behavior
`authorize` shouldn't be very slow on long path

## Current Behavior
https://github.com/networkservicemesh/deployments-k8s/issues/3053

**Comment by Mixaster995** [comment]
Made a few measurements for `authorize`. Used manually placed timers in unit tests.
Measured all unit tests in `opa` package, all of them shows same behaviour, so attached only results from `TestWithTokensPathValidPolicy`.

Results from timers shows that the main load is in `opa` method which evaluates prepared eval query
Our code from `PreparedOpaInput` takes much smaller amount of time and it is not required to be faster.
```
PreparedOpaInput took: 24.575µs
authorization policy init took: 195ns
Eval took: 186.801µs

PreparedOpaInput took: 14.562µs
authorization policy init took: 104ns
Eval took: 202.239µs

PreparedOpaInput took: 56.502µs
authorization policy init took: 220ns
Eval took: 334.326µs

PreparedOpaInput took: 29.403µs
authorization policy init took: 156ns
Eval took: 248.861µs
```

**Comment by Mixaster995** [comment]
Tested on integrated tests(nse-composition) and collected some results through logs.
Also collected pprof metrics from unit tests for finding correlations.

## Integration tests results
Resulted logs with worst result(longest time 190ms):
```
Nov  8 07:20:37.308[36m [INFO] [name:nsmgr-sbzxx] [0m(4)    ⎆ sdk/pkg/networkservice/common/authorize/authorizeServer.Request() span=452f5b0bef5da3a5:39ab4f17c56d1542:12c02a2467f7f2cd:1

Nov  8 07:20:37.308[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.1)      PreparedOpaInput took: 92.381µs
Nov  8 07:20:37.316 [DEBU] [name:nsmgr-sbzxx] (4.2)      authorization policy init took: 7.228359ms
Nov  8 07:20:37.317[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.3)      Eval took: 396.534µs

Nov  8 07:20:37.317[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.4)      PreparedOpaInput took: 50.327µs
Nov  8 07:20:37.376[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.5)      authorization policy init took: 58.864423ms
Nov  8 07:20:37.380[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.6)      Eval took: 1.422449ms

Nov  8 07:20:37.381[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.7)      PreparedOpaInput took: 101.708µs
Nov  8 07:20:37.412[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.8)      authorization policy init took: 30.383011ms
Nov  8 07:20:37.413[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.9)      Eval took: 1.023784ms

Nov  8 07:20:37.474[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.10)      PreparedOpaInput took: 2.953864ms
Nov  8 07:20:37.498[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.11)      authorization policy init took: 22.263525ms
Nov  8 07:20:37.498[37m [DEBU] [name:nsmgr-sbzxx] [0m(4.12)      Eval took: 576.166µs

Nov  8 07:20:37.499[36m [INFO] [name:nsmgr-sbzxx] [0m(5)     ⎆ sdk/pkg/networkservice/utils/metadata/metadataServer.Request() span=452f5b0bef5da3a5:279debe3c17f7bae:39ab4f17c56d1542:1

```
## `pprof` results
1000 runs of `TestWithTokensPathValidPolicy`:
![profile003](https://user-images.githubusercontent.com/26433765/140711107-7cf8fb63-e849-4e45-a210-4c74fa28facf.png)

10000 runs of  `TestWithTokensPathValidPolicy`:
![profile002](https://user-images.githubusercontent.com/26433765/140711055-e134f9f4-1fa4-4db3-a30a-911d04076ff7.png)

## Conclusions
Sufficent amount of time spent in `init` function, but only on first run(as expected), all subsequent runs are negligible(took nanoseconds to run). As `pprof` graph shows most of time split between opa func `prepare` and `syscall` which is reading policy source file.

I don't see much room for improvement here. For now, problem is mitigated with higher resources for nsm apps.

**Comment by denis-tingaikin** [comment]
@edwarnicke we are not found problems in authorize. So closing this.

**Comment by edwarnicke** [comment]
Looks good.
