### ISSUE TITLE
TestHealClient_FindTest  fails

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/sdk#1157]
## Current Behavior
without adapters in registry chains test `TestHealClient_FindTest ` fails https://github.com/networkservicemesh/sdk/runs/4176922797?check_suite_focus=true

## Details
Fails mostly on windows, once caught this on ubuntu
With enabled logs, test passes. Requires further investigation
caught this here caught this here https://github.com/networkservicemesh/sdk/pull/1149

**Comment by Mixaster995** [comment]
closed with https://github.com/networkservicemesh/sdk/pull/1186

**Comment by denis-tingaikin** [comment]
[logs_17303.zip](https://github.com/networkservicemesh/sdk/files/8800651/logs_17303.zip)
