### ISSUE TITLE
Heal: release resources before healing 

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#1166]
## Description
Currently we don't release all resources when `heal` starts. 
We call `Close()` before `heal` `Request` but it doesn't go through all of the `Path`.
https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/begin/event_factory.go#L98

## Use-case:

Let's take a look at the death of a nsmgr case:
`nsc --> nsmgr --> fwd--> nse`

**Steps**:
1. nsc calls request on nsmgr
2. All fine we got connection.
3. nsmgr died.
3. nsc starts healing, calls close:
`Close() : nsc --->x (died) nsmgr --fwd -- nse`
`Close()` **won't reach `nsmgr` and resource releasing will be interrupted.**
4. Call Request() from heal:
`heal Request() : nsc --> nsmgr(new) --> (interface name collision)fwd -- nse`

**Actual:** 
got interface name collision on fwd1 side. 

**Expected:**
all fine step 5 complete successful.

### 1.  Removing collisions by duplicating
In this case we should do:
1. Interface duplicates. If we already have interface with the same `name` (for example kernel on NSC, because we didn't remove it on `Close()` inside forwarder) we can create interface named `name + some suffix`
2. Use `/30` mask in integration-tests and use new IPs to check new connection (after heal)
So, we believe here that the connection after healing is a completely new connection.
Estimation: most likely, we can do it before the release

### 2. Improve heal (can't be done before release)

In this case we can start thinking in directions 
1. Call `Close()` after restart. For example if `nsmgr` restarted, we can try to get all connections from forwarders.
2. Think about the approach that was in the previous implementation - each element monitors the others (not just `NSC`)
Estimation: we can't do it before release

**Comment by denis-tingaikin** [comment]
@glazychev-art 

as I can see:

 `option 1` can be done before release. 
 `option 2` can't be done before release. 
 
Is this correct?

**Comment by glazychev-art** [comment]
@denis-tingaikin 
Yes

**Comment by edwarnicke** [comment]
@glazychev-art Why doesn't the forwarder recognize the connection id and treat it as a refresh?

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/sdk/pull/1167
