### ISSUE TITLE
Question on Refresh behavior

### ISSUE THREAD

**Issue by Sol-0** [networkservicemesh/sdk#1185]
## Question

Hi @edwarnicke ,

I was checking how refresh mechanism works in NSM during issue #839 investigation, and I think refresh might be broken in the case when different mesh elements (nsmgr, forwarders, etc.) have different token expiry.

I checked [your changes in this PR](https://github.com/networkservicemesh/sdk/pull/1083) and saw that, e.g. in [NSMgr server](https://github.com/networkservicemesh/sdk/pull/1083/files#diff-96982551d2cd428c0543ddf538cc804ca5ecbbf9f790cb35397046fb9413bb1dR213) refresh was removed, so after that I also checked [your discussion with Vladimir](https://github.com/networkservicemesh/sdk/pull/1083#discussion_r712823859) and found your response:
`"...We could do as you suggested and compute that in refresh. I'm tempted though to do it in updatetoken by clamping down expiretime to the smallest in the path on the return direction of the path."` - could you please share whether anything was done here? As I couldn't find a place in the code where this case is handled.

Also, if you don't mind, could you please describe how refresh mechanism is working currently?

**Comment by edwarnicke** [comment]
@Sol-0 Delighted to talk you through it :)

Let's start with the [Client Chain](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/chains/client/client.go#L44-L79).  It includes a [opts.refreshClient](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/chains/client/client.go#L62) in the chain.  By [default](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/chains/client/client.go#L49),  that opts.refreshClient is [refresh.NewClient](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L47-L51).  

However, if the user passes [client.WithoutRefresh()](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/chains/client/options.go#L106-L111) then opts.refreshClient is set to [null.NewClient](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/null/client.go#L38-L40) which is a noop.

This brings us around to the first central feature of refresh: It should only be performed by non-passthrough clients.
If a client is part of a passthrough chain element (like NSMgr, or a Forwarder, or [cmd-nse-firewall-vpp](https://github.com/networkservicemesh/cmd-nse-firewall-vpp) it should be using the client.WithoutRefresh() option to *not* do refresh.  Refresh is driven from the *start* of the chain, not the middle.

[The refresh chain element](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/refresh) on Request [computes the time after which it should send a refresh request](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L61-L67) which is [roughly 1/3 the time remaining till expiration plus a little bit of noise](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L127-L132).

The refresh chain element [creates a cancelCtx](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L70) [cancels any old cancelCtx from previous request](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L72-L74) and [stores the new cancelCtx](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L75).

From there a [go routine is spawned to send the refresh at the computed time](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L82-L96) and, if it does not succeed, keep trying to send it.

Note: if cancelCtx has been canceled (either by Close or a new Request) the go routine exits.

The comment you so astutely noted is that we should probably clamp down the expireTime to the earliest time in the chain.
IMHO the best way to do that is to have [updatetoken](https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/updatetoken/common.go#L63) compare its expireTime to the expireTime of the next PathSegment after it in the Path, and pick the earliest.

**Comment by denis-tingaikin** [comment]
> The comment you so astutely noted is that we should probably clamp down the expireTime to the earliest time in the chain.
IMHO the best way to do that is to have updatetoken compare its expireTime to the expireTime of the next PathSegment after it in the Path, and pick the earliest.

I think we need to implement this. I see that it can be super useful for interdomain scenarios where two clusters can have a  totally different spire setup. 

@edwarnicke Do you mind if we'll create an issue and describe a potential technical solution for this?

**Comment by edwarnicke** [comment]
@denis-tingaikin Please do

**Comment by Sol-0** [comment]
@edwarnicke ,
thanks a lot for really helpful and in-depth explanation!

@denis-tingaikin ,
I've added a new issue #1189 based on this discussion.
