### ISSUE TITLE
Advanced healing: datapath was down

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#1187]
## Overview

Let's consider a case when our control plane works fine - we established a `connection`, requests from `nsc` to `nse` pass with no errors. With `refreshes`, we just maintain this connection. 

But what if the _**data plane**_ was down - for example, parameters for routing were changed accidentally, or the interface is frozen or dead.
The current healing will not be able to fix this, because the `connection` has been established and there are no problems with further `requests`.

Requests:
```
┌─────────┐         ┌─────────┐         ┌─────────┐        ┌─────────┐
│         ├────────►│         ├────────►│         ├───────►│         │
│   NSC   │         │  NSMGR  │         │   FWD   │        │   NSE   │
│         │◄────────┤         │◄────────┤         │◄───────┤         │
└─────────┘         └─────────┘         └─────────┘        └─────────┘
```
Ping:
```
 ┌─────────┐        ┌─────────┐        ┌─────────┐
 │         │        │         │        │         │
 │   NSC   ├───────►│   FWD   ├──►X    │   NSE   │
 │         │        │         │        │         │
 └─────────┘        └─────────┘        └─────────┘
```

### 1. Use `WithLivelinessCheck` option for `healClient`

https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/heal/options.go#L34

On the client side we already have all of the parameters (`ip-addresses`, `routes`), with which we can check the status of the connection.
With this option we can create a goroutine, that will periodically send an `icmp` packet to the endpoint. 
For example, if `nsc` has:
- `kernel` interface - we can try to use `icmp` package https://pkg.go.dev/golang.org/x/net/icmp or https://github.com/go-ping/ping
- `memif` interface - we need to implement a new `Checker`, that will run `ping` from `vpp`.

If ping fail - send a faulty connection to the channel, that will be processed by `healClient` like an event from `MonitorConnections` ([Link](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/heal/eventloop.go#L95)).
`healClient` will start its work and call `Close` and `reRequest`.

**Example:**
Let's take a look at local `Kernel2Kernel` scenario.
**_Steps:_**
1. Create NSC with `healClient` option:
```
WithLivelinessCheck(func(conn *networkservice.Connection) bool {
 // ping(conn.IpContext.DstIPAddr)
 // if !ping {
 //      return false
 // }
 // return true
})
```
2. NSC sends Request
3. NSC receives a response from NSE
4. NSC call `ok := LivelinessChecker()` on a successful response.
5. If `!ok` - return an `error` to previous elements.
6. If `ok` - NSC starts `LivelinessChecker` goroutine (with some empirical period ~ `1s`).
7. If `LivelinessChecker` returns false - start healing 

### 2. Add a sidecar for `nsc`
We can also try to use sidecars for NSC. 
Each sidecar will contain `DatapathChecker` (that implements `ping`) for one mechanism.

**Example:**
Let's take a look at local `Kernel2Kernel` scenario.
**_Steps:_**
1. Create NSC with a `DatapathSidecar`, that implements ping for a `kernel` interface.
2. `DatapathSidecar` starts to monitor `nsmgr` to get new connections.
2. NSC `healClient` starts to monitor `DatapathSidecar` to get connections, that are not "pingable".
3. NSC sends Request
4. NSC receives a response from NSE
5. If NSC receives an event from `DatapathSidecar` - start healing

**Comment by denis-tingaikin** [comment]
@glazychev-art Could you add a scenario with steps on how will work both solutions?

**Comment by edwarnicke** [comment]
@glazychev-art Its interesting you bring this up... because I've been thinking on another related issue where the control plane chain goes 'DOWN', for example because the remote NSMgr has gone down, but the datapath stays up (so ping keeps working).

So I think we may have three interesting cases here:
1. Check datapath from client on return from Request
2. Check datapath from client on 'DOWN' event from Monitor
3. Check datapath ongoing

1 and 2 are logically simple.  3 begs the question: how often.

@glazychev-art Thoughts?

**Comment by glazychev-art** [comment]
@edwarnicke 
maybe i missed something..

2. Check datapath from client on 'DOWN' event from Monitor

Could you please tell more about this? How is this different from the current healing? So, for example, we checked the datapath and regardless of whether it is 'UP' or 'DOWN' - we do all the usual healing procedures. 
Because, if it is 'UP' - it's incorrect, because control plane is already 'DOWN' and we have no other mechanisms than to call `Close` and `Request` (current healing).
If it is 'DOWN' - no doubt that healing should be started.
Isn't it?

**Comment by glazychev-art** [comment]
@edwarnicke 
We've added a new solution in description.
So, now we have 2 options:
1. Use `WithDatapathChecker()` option for `healClient`
2. Use sidecar for `NSC`
What do you think is the most acceptable?

**Comment by glazychev-art** [comment]
We also thought about the following scenario.

Control plane goes 'DOWN', for example because the remote NSMgr has gone down, but the datapath stays up (so ping keeps working).
Do we need to call `Close` on heal, before new `Request` in this case? If we call _**only**_ `Request` - it will be like a refresh scenario, and our datapath will remain working.

**Comment by edwarnicke** [comment]
> @edwarnicke maybe i missed something..
> 
> 2. Check datapath from client on 'DOWN' event from Monitor
> 
> Could you please tell more about this? How is this different from the current healing? So, for example, we checked the datapath and regardless of whether it is 'UP' or 'DOWN' - we do all the usual healing procedures. Because, if it is 'UP' - it's incorrect, because control plane is already 'DOWN' and we have no other mechanisms than to call `Close` and `Request` (current healing). If it is 'DOWN' - no doubt that healing should be started. Isn't it?

Take the following example:

nsc -> nmgr1 -> forwarder1 -> nsmgr2 -> forwarder2 -> nse

Say nsmgr2 goes 'DOWN'.  Monitor propogation from nsmgr2 gets to forwarder1 and then nsmgr1 and finally to nsc.
NSC checks the dataplane.  The dataplane is fine because forwarder1, forwarder2, and nse are still fine.

So the NSC does *not* Close the Connection and attempt to heal (because the dataplane is fine).

**Comment by glazychev-art** [comment]
@edwarnicke
Ok let's continue with this example and iterate over all the possible options.
Our current (in main branch) healing - we receive monitor events and if this is `networkservice.State_DOWN` - start healing `WithReselect()` - call Close and Request. Without `reselect` - only Request.

We can have:
Controlplane (CP) states - `UP`/`DOWN`
and
Dataplane (DP) states - `UP`/`DOWN`

I guess our behavior will be like this:
1. CP = `UP`, DP = `UP` - all is fine
2. CP = `UP`, DP = `DOWN` (interface freezes on NSE for example) - use our current healing `WithReselect()`.
3. CP = `DOWN`, DP = `UP` (nsmgr2 died) - use our current healing _**without**_ Reselect. Because we already have working ping, we only need to fix our ControlPalne
4. CP = `DOWN`, DP = `DOWN` - this is bad, use our current healing `WithReselect()`.

 @edwarnicke 
 Do you see any problems here?

**Comment by edwarnicke** [comment]
@glazychev-art 
> 3. CP = DOWN, DP = UP (nsmgr2 died) - use our current healing without Reselect. Because we already have working ping, we only need to fix our ControlPalne

OK... this case is really smart and had not occurred to me.  You are completely correct here :)

Cases 1,2 and 4 where what I was originally thinking... but case 3 is just brilliant, lets do that too :)

**Comment by glazychev-art** [comment]
@edwarnicke 
OK, cool!

So, now we have 2 options (see issue Description):

1. Use `WithDatapathChecker()` option for `healClient`
2. Try to use sidecar for `NSC`

What do you think is the most acceptable?

**Comment by edwarnicke** [comment]
I think we already have an option [WithLivelinessCheck](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/heal/options.go#L34) that does what you are talking about for WithDatapathChecker().  Would it make sense ot use that?

**Comment by glazychev-art** [comment]
Yes, thank you!

**Comment by glazychev-art** [comment]
So, I think we need:
1. Implement the first solution in sdk (_**Use WithLivelinessCheck option for healClient**_)
2. Add `livelinessChecker` to `sdk-kernel` to ping from kernel interfaces. We can try to use: https://github.com/go-ping/ping or https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/main/internal/tests/suite_kernel_test.go#L265
3. Add `livelinessChecker` to `sdk-vpp` to ping from memif interfaces. We can try to use: https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/main/internal/tests/suite_memif_test.go#L147
4. Update `cmd-nsc` and `cmd-nsc-vpp` with livelinessChecker option.
5. Add `deployment-k8s` examples. For example, we can kill the interface on the endpoint manually.

**Comment by glazychev-art** [comment]
@edwarnicke 
What do you think, is it supposed to use the `LivelinessCheck` in the goroutine for continuous checking?
(see **_Solutions_** - _Use WithLivelinessCheck option for healClient - Step 6_)

**Comment by glazychev-art** [comment]
@edwarnicke
Eventually we chose to run `LivelinessCheck` only on refreshes.

So, I have tested `3 case` from this comment -  https://github.com/networkservicemesh/sdk/issues/1187#issuecomment-990597713 - and faced a problem: 
_NSE pod can be **pingable** even if it was deleted._

For example:
`NSC -> .... -> NSE `
1. Successful `Request` and ping. CP = `UP`, DP = `UP`
2. Delete NSE.
3. Receive Monitor `DOWN` event. CP = `DOWN`
4. Let's check DP, run ping.
5. Ping works. 
I've used [exechelper](https://github.com/edwarnicke/exechelper) and [go-ping](https://github.com/go-ping/ping) inside NSC. 
Ping works until application (exechelper or go-ping) sends packets. No matter how many and how long.
Moreover, if I start ping from the `shell` - this also works as long as the ping from the application works.
But, if the ping from application is not used - `shell` ping stops very fast (~1-2 seconds after NSE's death). 

I've tested it locally on `kind` and on `GKE` cluster. And also tried to use `Deployment` and `Pod` types - the result is the same.

**_Note_**: if I set NSE interface down manually - ping from application also stops. This is correct.

We have two questions:
1. Is it normal to use [exechelper](https://github.com/edwarnicke/exechelper) or [go-ping](https://github.com/go-ping/ping) ?
2. Maybe we should always use `WithReselect()` option, even if only CP is `DOWN`. In this case, we can avoid the problem described above.

**Comment by glazychev-art** [comment]
I have been investigating an issue related to strange ping behavior. 
The root cause is `L2/L3 cross-connect`. For some reason, it "locks" the interface from the already deleted network namespace.
I was able to reproduce this on bare vpp.

The issue was reported.
JIRA-issue: https://jira.fd.io/browse/VPP-2006
Discussion: [Link](https://lists.fd.io/g/vpp-dev/topic/l2_l3_cross_connect_allows/88392642?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,88392642,previd=1642059333598535502,nextid=1640176417996351680&previd=1642059333598535502&nextid=1640176417996351680)

**Comment by edwarnicke** [comment]
> * Add `livelinessChecker` to `sdk-vpp` to ping from memif interfaces. We can try to use: https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/main/internal/tests/suite_memif_test.go#L147

This is very odd... if the NSE is down: what is replying to the icmp echo request?

**Comment by edwarnicke** [comment]
@artem-belov OK... I've read the issue you wrote.  Here's what's going on.

As far as the kernel is concerned, the netns is a going concern as long as the netns file is either (a) linked somewhere in the filesystem or (b) open by some process... the netns is still a going concern and so it won't clean it up.

So what is happening here is that vpp has the netns file open, and so it's not getting cleaned up.

What to do about this is an interesting question.

**Comment by edwarnicke** [comment]
@glazychev-art Do the liveliness checks work for everything but NSE death involving kernel interfaces in the NSE?

**Comment by glazychev-art** [comment]
Closed - https://github.com/networkservicemesh/sdk/pull/1271
