### ISSUE TITLE
`Refresh` client should calculate the shortest token expiry time

### ISSUE THREAD

**Issue by Sol-0** [networkservicemesh/sdk#1189]
## Expected Behavior
`Refresh` client should calculate the shortest token expiry in the chain. This is required for refresh feature to work correctly in the case when there're multiple mesh elements with different token expiry (e.g. in inter-domain case).

## Current Behavior
The shortest token expiry is not calculated.

## Context
Bug is opened based on discussion in #1185.

## Proposed Solution
`Refresh` client can iterate over path segments and calculate the shortest token expiry.

**Comment by denis-tingaikin** [comment]
I would be suggested to do something simple here: https://github.com/networkservicemesh/sdk/blob/404ad8a93c2f8520dc70b6101047ca0c9ff839f5/pkg/networkservice/common/refresh/client.go#L111

```go
var expireTime
for _, segment := range len(conn.GetPath().GetPathSegements()) {
        expires, err := ptypes.Timestamp(segmet).GetExpires())
	if err != nil {
		return 0, errors.WithStack(err)
	}
	 if expires < expireTime { // TODO
	 	 expireTime = expr
	 }
}
```
