### ISSUE TITLE
Enable mutually aware NSEs

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/sdk#1203]
## Description
Now `excludedprefixes/client.go` prevents `IPs` overlapping between NSEs.
We need to support use case where it is ok.
Accordingly to changes in `api` (https://github.com/networkservicemesh/api/issues/123) modify `pkg/networkservice/common/excludedprefixes/client.go` chain element to enable mutually aware NSEs.
Use `group_id`(if it's not empty) to **not** add `IPs` issued by nse to excluded prefixes for next requests to same nse group.

## Issue
part of https://github.com/networkservicemesh/api/issues/121

## References
chain element for modification - https://github.com/networkservicemesh/sdk/pull/1197/files#diff-feb7f1b8d36ba643d92d8e4ab16439209955c0c88b3500ef93e2479509ba69af

## Definition of done
- Modify `excludedprefixes/client.go`
- Add unit testing
- Add new chain element or modify already existing to fill `group_id` field on nse side

**Comment by denis-tingaikin** [comment]
Done by https://github.com/networkservicemesh/sdk/pull/1235
