### ISSUE TITLE
NSMgr should try to re-use previously selected forwarder in case of restart

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1230]
## Steps to Reproduce

1. Deploy NSMgr, forwarder1, registry
2. Deploy nsc and nse for service "my-ns"
3. Wait for nsc request to complete
4. Deploy forwarder2,  forwarder3
5. Restart NSMgr

## Expected Behavior

NSMgr selects the previously selected forwarder (forwarder1) for nsc on restarting. Datapath is still alive.

## Current Behavior

NSMgr selects the first forwarder for registry response (it could be forwarder1, forwarder2, forwarder3) for nsc on restarting.  Previous datapath that is alive may be closed and another one may be created(!).

**Comment by denis-tingaikin** [comment]
@edwarnicke Can we consider this issue?

**Comment by edwarnicke** [comment]
Yes.  Question though, how does this relate to the discussion about forwarder loadbalancing?

**Comment by denis-tingaikin** [comment]
>how does this relate to the discussion about forwarder loadbalancing?

The problem could be considered as part of forwarder load-balancing.  But as we don't want to add forwarder load-balancing at this moment we could consider the problem separatly.

**Comment by denis-tingaikin** [comment]
@edwarnicke Can we add this into 1.3.0 project board?

**Comment by edwarnicke** [comment]
@denis-tingaikin Please do add it.

**Comment by edwarnicke** [comment]
@denis-tingaikin The really interesting questions here is going to be the balancing question between doing something about this and the cost of doing something about this... so whether we do it will depend a lot of the space of available solutions.

**Comment by edwarnicke** [comment]
@denis-tingaikin What ideas do we have on how to deal with the situation?

**Comment by denis-tingaikin** [comment]
Done by #1232
