### ISSUE TITLE
Begin merge connection strategy

### ISSUE THREAD

**Issue by LionelJouin** [networkservicemesh/sdk#1231]
## Overview

Together with the new [source routing feature](https://github.com/networkservicemesh/api/issues/119), we would like our NSCs to have the ability to re-configure their connections on the fly, so without having to close, and re-request (mostly to update the IP context). But currently, the begin client chain component is preventing this due a merge function supporting only the extracontext for now. 

Here is the [link to the function](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/begin/merge.go#L39), my proposal would be to not merge the ip contexts and only keep the requested one.

## References

https://github.com/networkservicemesh/api/issues/119
https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/begin/merge.go#L39

**Comment by denis-tingaikin** [comment]
Hmm. Can this be related to https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/441?

**Comment by LionelJouin** [comment]
yes, from what I understood it seems related. So far, the only blocking element is the begin chain component. I tried with the changes in my environment and it worked fine (my NSC re-request with updated source IPs and policies)

**Comment by LionelJouin** [comment]
Solved: https://github.com/networkservicemesh/sdk/pull/1238
