### ISSUE TITLE
matchEndpoint Function Improvement

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1239]
## Expected Behavior

[matchEndpoint](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/discover/match_selector.go#L28) function should match request labels with NSE labels even if `NetworkService` doesn't contain labels at all. NSEs should be sorted by priority where priority is determined by the number of matches of NSE labels with request labels.

## Current Behavior

[matchEndpoint](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/discover/match_selector.go#L28) function doesn't check labels from request if `NetworkService` doesn't contain any.

## Possible solution
Change [IsSubset](https://github.com/networkservicemesh/sdk/blob/793dfca17be51cbca8982f64612d73185eeab597/pkg/tools/matchutils/utils.go#L50) function to return number of matches instead of boolean value

**Comment by denis-tingaikin** [comment]
Looks like enhancement. 

@edwarnicke Can we implement this?

**Comment by denis-tingaikin** [comment]
Finally we are realized that match selectors are good for this kind issues.
