### ISSUE TITLE
Test_RefreshNSEClient_SetsCorrectExpireTime is unstable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1253]
## Expected Behavior

Test_RefreshNSEClient_SetsCorrectExpireTime is stable.

## Current Behavior
Test_RefreshNSEClient_SetsCorrectExpireTime is unstable.

## Failure Information (for bugs)

Build - https://github.com/networkservicemesh/sdk/runs/5813211329?check_suite_focus=true

## Steps to Reproduce

Run Test_RefreshNSEClient_SetsCorrectExpireTime is unstable a few times on Ci

## Failure Logs
```
--- FAIL: Test_RefreshNSEClient_SetsCorrectExpireTime (0.24s)
    nse_registry_client_test.go:249: 
        	Error Trace:	nse_registry_client_test.go:249
        	Error:      	Condition never satisfied
        	Test:       	Test_RefreshNSEClient_SetsCorrectExpireTime
```

**Comment by glazychev-art** [comment]
Close with https://github.com/networkservicemesh/sdk/pull/1254
