### ISSUE TITLE
Update everything to go 1.18

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1264]
## Overview

All our code are based on go 1.16. We could update everything to go 1.18 and  schedule refactorings based on generics to simplify many things in our codebase.

**Comment by denis-tingaikin** [comment]
@edwarnicke Does it make sense for v1.4.0?

**Comment by edwarnicke** [comment]
Yes :)

**Comment by denis-tingaikin** [comment]
Looks done
