### ISSUE TITLE
TestNSMGR_HealRegistry is unstable

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1276]
## Expected Behavior

TestNSMGR_HealRegistry is stable

## Current Behavior

TestNSMGR_HealRegistry is unstable

## Failure Information (for bugs)
https://github.com/NikitaSkrynnik/sdk/runs/6289717178?check_suite_focus=true

## Failure Logs

[ci_logs.zip](https://github.com/networkservicemesh/sdk/files/8620813/ci_logs.zip)

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/sdk/pull/1301
