### ISSUE TITLE
NSM Control Plane apps are using expired spire tls cert in interdomain scenarios

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1298]
## Expected Behavior

NSM Controlplane apps are not using expired spire tls certs

## Current Behavior

NSM Controlplane apps are using expired spire tls certs

## Steps to Reproduce

1. Run interdomain example.
2. Wait for 1h (or change ttl time to 10-20min)
3. See at clients logs

**Comment by NikitaSkrynnik** [comment]
I've tested interdomain examples (on main branch) with different values.
TestKernel2Vxlan2Kernel:
1. TTL = 3m - no errors
2. TTL = 5m - no errors
3. TTL = 10m - no errors
4. TTL = 30m - no errors
5. TTL = 1h - no errors

TestFloatingKernel2Vxlan2Kernel:
1. TTL = 5m - no errors
2. TTL = 10m - no errors
3. TTL = 30m  - no errors
4. TTL = 1h - no errors

**Comment by denis-tingaikin** [comment]
Looks valid, closing this by  https://github.com/networkservicemesh/sdk/issues/1298#issuecomment-1143355043
