### ISSUE TITLE
dns: dnscontext doesn't restore `resolv.conf`

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#1339]
## Current Behavior

dnscontext doesn't restore `resolv.conf` after restarts

## Failure Information (for bugs)

If the NSE restarts dnscontext cannot find previous `resolv.conf` (/etc/resolv.conf.restore). But the current `resolv.conf` is also invalid - it contains already modified values (`nameserver 127.0.0.1 ...`)

## Steps to Reproduce

Integration tests:

1. Add logs to an NSC to print the current `resolv.conf` - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/connectioncontext/dnscontext/client.go#L123
2. Delete `nsmgr` from from the nsm-system kustomization file
3. Run any of integration tests (Kernel2Kernel)
4. `kubectl get logs {nsc_name}`
5. See that the first output is fine, but the second (after restart) contains invalid values (already modified).

## Context

* Kubernetes Version:
* etc.

**Comment by denis-tingaikin** [comment]
Seems like fixed.
