### ISSUE TITLE
Authorize on timeout

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/sdk#1398]
## Current Behavior

Now there may be a problem with closing the connection on `timeout`, since the timeout mostly happens when the token expires. 
After that, `Close` is called, but it fails on `authorize`, because token is already expired.

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by glazychev-art** [comment]
The general idea is to call `timeout`/`expire` in advance, considering the request timeout.

Steps:
- [ ] **networkservice**: consider request timeout before calling [Close](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/timeout/server.go#L71)
- [ ] **networkservice**: sandbox test
- [ ] **registry**: `updatepath` should update nse.ExpirationTime (skipped values [here](https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/updatepath/nse_server.go#L48-L52))
- [ ] **registry**: `expire` updates expirationTime to default value only if it was not set. Call `Unregister` in advance
- [ ] **registry**: sandbox test
- [ ] manual integration testing

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/networkservicemesh/sdk/pull/1404
