### ISSUE TITLE
Add coverage check on CI

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#142]
## Motivation

The coverage check might help to review PRs with tests.

**Comment by denis-tingajkin** [comment]
@edwarnicke assign the issue to me if this is actual.

**Comment by denis-tingajkin** [comment]
@edwarnicke Can we do this issue? :)

**Comment by glazychev-art** [comment]
Closed - https://github.com/networkservicemesh/sdk/pull/1408
