### ISSUE TITLE
Memory DNS Handler handles requests incorrectly if it doesn't have the required DNS record.

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1442]
## Expected Behavior

Memory DNS handler handles requests with empty answers correctly.

## Current Behavior

Memory DNS handler handler requests for non-existent records incorrectly. Some utilities (ping, for example) don't work because of this.

## Steps to Reproduce

1. Run vl3-dns example
2. Ping one alpine from another alpine using its dns name without `-4` flag

## Failure Logs
[logs.txt](https://github.com/networkservicemesh/sdk/files/11092655/logs.txt)

**Comment by denis-tingaikin** [comment]
Seems like fixed by https://github.com/networkservicemesh/sdk/pull/1443
