### ISSUE TITLE
Use counters instead of histogram

### ISSUE THREAD

**Issue by LionelJouin** [networkservicemesh/sdk#1464]
## Overview

From what I saw, currently, the only component using the metrics [API](https://github.com/networkservicemesh/api/blob/v1.9.0/pkg/api/networkservice/connection.proto#L44) is the [SDK-VPP](https://github.com/networkservicemesh/sdk-vpp/blob/v1.9.0/pkg/networkservice/stats/common.go#LL65C41-L65C79) that collects the rx_bytes, tx_byes, rx_packets, tx_packets and drops. Counters would be more appropriate for these kind of metrics instead of histogram.
  
https://github.com/networkservicemesh/sdk/blob/v1.9.0/pkg/networkservice/common/metrics/server.go#L65

## Link to the Google Docs document

Discussed on 30th May during the community meeting.

## References

https://opentelemetry.io/docs/concepts/signals/metrics/

**Comment by denis-tingaikin** [comment]
- Change sdk ~1h
- Test opentelemetry https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/observability/jaeger-and-prometheus ~7h
- Open PR/provide feedback ~ 2h

TOTAL: 10h

**Comment by LionelJouin** [comment]
Closed with https://github.com/networkservicemesh/sdk/pull/1467
