### ISSUE TITLE
kernel NSC with multiple NetworkServices

### ISSUE THREAD

**Issue by or-adar** [networkservicemesh/sdk#1486]
my knowledge is very limited, so I would like to know if I should use other approach that can suit my use case.

I have a pod in my cluster running NSC as a container,
I want it to connect to a large number of Network Services, so I'm expected to have multiple kernel interfaces injected to my pod's  network namespace and multiple routing tables as well,
since in kernel mechanism, a routing table is expected to be injected for each connection ID (and NSC generates connection ID for each NS it wants to connect to).

Now, AFAIK, the linux kernel supports up to 252 additional routing tables. so it looks like I'm limited here to the number of possible Network Services I am allowed to Request.
Should I not use kernel mechanism? is there other alternatives or approaches to what I'm trying to acheive?

**Comment by glazychev-art** [comment]
@or-adar 
This is a good question. Now we add routes to all NetworkServices in only one main table.

Let's say we have a new chain element that adds each new route to a separate routing table.
I'm not sure, but if we take a look at the iproute2 manual https://man7.org/linux/man-pages/man8/ip-route.8.html:
```
Route tables: Linux-2.x can pack routes into several routing
       tables identified by a number in the range from 1 to 2^32-1 ...
```
Am I missing something?

**Comment by glazychev-art** [comment]
@or-adar 
Always happy to help!
Can we close the issue?

**Comment by or-adar** [comment]
sure!
