### ISSUE TITLE
Endless retries on error

### ISSUE THREAD

**Issue by Natush** [networkservicemesh/sdk#1500]
Hi :)

I hope this is the right location for the following question.
I'm using NSM which was forked from 1.6.

If a Close was triggered by an error (for example, from the forwarder), then the NSC can get a close callback, but still NSM seems to re-try on that same closed connection info.
And if that re-attempt fails, it continue with endless retries.
 
In addition, if a connection refresh failed with some error, again I see endless retries, to heal/refresh the connection.

Question is, is this the expected behavior? 
If so, is there a configuration to set a retry limit, or some time threshold? 
I was expecting NSM_MAX_TOKEN_LIFETIME to be used as a retry limit, but instead we are reaching endless retries which are failing on: "no sufficient privileges".

Thanks,
Einat.

**Comment by NikitaSkrynnik** [comment]
Can't reproduce this bug on main branch
