### ISSUE TITLE
TestNSMGRHealEndpoint_DatapathHealthy_CtrlPlaneBroken is unstable

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1573]
## Runs

1. https://github.com/networkservicemesh/sdk/actions/runs/7470398510/job/20329023859
[logs_24332.zip](https://github.com/networkservicemesh/sdk/files/13883136/logs_24332.zip)

2. https://github.com/networkservicemesh/sdk/actions/runs/7470356171/job/20328914425
[logs_24326.zip](https://github.com/networkservicemesh/sdk/files/13883141/logs_24326.zip)

**Comment by NikitaSkrynnik** [comment]
Tested 3000 times on CI:
https://github.com/networkservicemesh/sdk/actions/runs/12117167184/job/33779056630?pr=1699

**Comment by NikitaSkrynnik** [comment]
15000 times on CI:
https://github.com/networkservicemesh/sdk/actions/runs/12173847532/job/33954853808?pr=1699

**Comment by denis-tingaikin** [comment]
Seems like done 
https://github.com/networkservicemesh/sdk/issues/1573#issuecomment-2519530243
