### ISSUE TITLE
Option to disable control characters in logs

### ISSUE THREAD

**Issue by bszirtes** [networkservicemesh/sdk#1594]
It would be nice if there were an option to disable coloring and remove control characters from the logs.

**Comment by denis-tingaikin** [comment]
Hello @bszirtes ,

We think that we can just remove some control characters in logs without options.

Could you also attach an example of logs with colouring and control characters that you would like to remove?

**Comment by bszirtes** [comment]
Hello @denis-tingaikin,

The control characters we want to exclude from the logs are closely related to the coloring, to the best of my knowledge. We would like to avoid the following:

```
Feb 22 06:38:57.984.[36m [INFO] [cmd:/bin/forwarder] .[0mStartup completed in 7.874008959s
```

Instead, what we would like to have, are the plain logs:

```
Nov 15 14:39:42.385 [INFO] [cmd:/bin/forwarder] Startup completed in 5.65923051
```

**Comment by denis-tingaikin** [comment]
As far as I know, we don't have colouring. Also, I suggest just removing all control symbols and not adding new options.
