### ISSUE TITLE
OPA leaks 

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1622]
## Motivation

![image](https://github.com/networkservicemesh/sdk/assets/49399980/bf873c22-1a1b-468e-8368-5fb38fd0c229)

Related to https://github.com/networkservicemesh/cmd-nsmgr/issues/675

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik memprofile is
[memlimit1.zip](https://github.com/networkservicemesh/sdk/files/15248679/memlimit1.zip)

**Comment by NikitaSkrynnik** [comment]
Don't see any problems in the last release candidate
