### ISSUE TITLE
High-load testing of NSM with new fixes

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1633]
## Description

We need to test NSM v1.13.1-rc.1 for memory leaks with these fixes:
1. https://github.com/networkservicemesh/sdk/pull/1628
2. https://github.com/networkservicemesh/sdk/pull/1631

## Tasks
| Task | Time | Done |
| ------ | ------- | ------- |
| Build images | 1h | |
| High-load testing | 7h |  |
| Check results | 2h | |

**Comment by denis-tingaikin** [comment]
Is this done or it's still TODO?

**Comment by denis-tingaikin** [comment]
Fixed by https://github.com/edwarnicke/grpcfd/pull/30 and https://github.com/networkservicemesh/sdk/pull/1616
