### ISSUE TITLE
trace chain element consumes too many resources

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1667]
## Main Issue
https://github.com/networkservicemesh/sdk/issues/1666

## Description
`context.WithValue` is used in many places (especially in `trace` chain element). It makes `ctx` very heavy and significantly slows down some operations like `postpone` which are also used in many chain elements. As a result `forwarder` can spend several seconds only on `postone`.

## Solution
Make contexts light and use connection's metadata instead.

**Comment by denis-tingaikin** [comment]
left side with enabled trace chain element , right side with disabled trace chain element

memory: 
![image](https://github.com/user-attachments/assets/efe6aed1-127b-44c3-84c6-508ce440d4ca)


cpu:
![image](https://github.com/user-attachments/assets/9ea518b4-452f-47be-8425-59d238a4248c)
