### ISSUE TITLE
Generalize authorize chain element

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/sdk#200]
The current chain element looks *only* at the last token in the path chain.  This is insufficient for the full spectrum of policy we are likely to want to enforce.

Expand on the authorize chain element by providing as its 'input' object:

1.  The Connection
2.  The TLSInfo (as retrieved by peer.FromContext for Server or grpc.Peer for the client)
3.  Operation - One of Request/Close
4.  Role - One of Client/Endpoint

**Comment by edwarnicke** [comment]
Related to #51

**Comment by lazyniv** [comment]
How do you think, do we need to add all of the TLSInfo.State content into the OPA input? Or we need to add only a X509SVID certificate from TLSInfo.State. I think that in our cases we only need a pem-encoded X509SVID certificate to verify the signature of the jwt token using the [built-in OPA functions](https://www.openpolicyagent.org/docs/latest/policy-reference/#using-pem-encoded-x-509-certificate). Of course we also need to add the spiffeID from this certificate to OPA input

**Comment by edwarnicke** [comment]
@lazyniv I think you are right on wrt just using the pem-encoded X509SVID :)
