### ISSUE TITLE
Registry: add join chain element

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#313]
## Description

Registry `join` chain element will add a possible to aggregate a few registry clients to one. It will be useful for cmd-nsmgr. For example, we can join memory registry and real registry client.

**Comment by edwarnicke** [comment]
What do you see 'join' doing? (I can imagine lots of useful things it could be doing... am curious which one wrt name choice :) ).

**Comment by denis-tingajkin** [comment]
@haiodo can you share examples of usage of join element in nsmgr?

**Comment by denis-tingajkin** [comment]
@edwarnicke we've little bit discussed  with @haiodo and found that at this moment we not need join element because of in nsmgr side we can simply add if block. For example 
```
if localRegistry is not found {
useLocalMemoryServer()
} else {
 connectToLocalRegistry()
}
```

**Comment by edwarnicke** [comment]
Cool :)
