### ISSUE TITLE
Interdomain: add registry chain element to proxying registration/find/unregistration to next registry

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#349]
## Context

https://github.com/networkservicemesh/sdk/issues/235

## Description

We need to add possible to registries proxy all incoming **registrations**/**unregistratiom**/**find** to the next registry. 

### Use-case:

1. The registry receives registration with a special symbol in the name "@" or special label in labels.
2. The registry just proxying this traffic to the next registry.

## Questions:

Do we want to use special symbol "@" in ns/nse name to mark it as interdomain? As an alternative variant, we can add special labels for nse. For example:

```
nse:
  name:
  labels:
   icmp-responder:
     k:v
   interdomain:
     k:v
```

**Comment by edwarnicke** [comment]
Simplistcally, yes, the @ means its coming from another registry, and so while we may *cache* information about it, we are never authoritative.  It is probably helpful however to think of *any* registry entry as having a network service mesh domain.

For example, the network service mesh domain of our local cluster may be named with a cluster name of some sort (cluster1.example.com for example).  Local users could skip the @cluster1.example.com, but the local registry is still for a domain, and if anyone outside the cluster is to be able to access it, it will need to have a name for that domain.

**Comment by edwarnicke** [comment]
There are some other ideas which may be interesting to think about.  You could imagine, even if our cluster local domain was never accessible outside the cluster, that you could think of it as @local.  Its also possible that you might choose to run multiple network service mesh domains in a single cluster, scoped per K8s namespace, so you might @my-namespace.nsm.local or @my-namespace.nsm.${clustername}.

Please note, all of this is 'things to think about' not 'directions to go do a thing'.  Leave space for such things, but don't let them impede your progress :)
