### ISSUE TITLE
Interdomain: add registry connect chain element

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#362]
## Context

https://github.com/networkservicemesh/sdk/issues/235

## Description

Proxy registry should be able to connect to the registry from another domain by the domain name. 

## Solution

Add analog of chain element [connect](https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/common/connect/server.go#L53) for registries.  

Example of usage:

1. Proxy registry receives  query with network service name = `ns-1@my.domain`.
2. Proxy registry resolves domain my.domain to IP.
3. Proxy registry connects to the next registry by IP from step2.

**Comment by edwarnicke** [comment]
I’d recommend breaking it into two chain elements: one that resolves ns-1@my.domain to and IP, and another that does the connect behavior.  That way we can start with the simple ‘look up a SRV record in DNS approach’ ... and if folks have other needs they only have to replace the chain element that does the resolutions.

**Comment by denis-tingajkin** [comment]
@edwarnicke it is a great idea! Will do, thanks
