### ISSUE TITLE
Adapters ignores context from adpated client/server

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#366]
## Problem statement

We need to store context from the adapter server/client and pass it to the next client/server to avoid the problem with losing 
values from adapted server/client context.

Note: Here we are passing context https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/core/adapters/client_to_server.go#L41
and actually all values from the chain are losing.

## Solution
 
1. Use here reference to the context instead of boolean flag https://github.com/networkservicemesh/sdk/blob/f833e641eb9b76b704dc0bae105c2911366eac6e/pkg/networkservice/core/adapters/context.go#L32 and apply changes to fix compilation errors
2. Pass context from the adapted chain serve/client to the next client/server.
3. Add test to cover

**Comment by edwarnicke** [comment]
What I've done for the vppagent config is simply to store a pointer to the vppagent config at the point before we hit the embedded client.  Please note, this is also a potential issue for the connect chain element etc.

That works simply and elegantly for that case, but I could see others that would be more problematic.

What specific case prompted this Issue?

**Comment by denis-tingajkin** [comment]
@edwarnicke Here is by context meaning context that passed on Request/Close/Find/Register, just `context.Context`. 

Previously if adapted client used context.WithValue("key", "value") then next server not finding value by "key". 

@ekanufrienko Has fixed this problem by #393 :)
