### ISSUE TITLE
[Question] Should we put README.md file to each chian element pkg?

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#380]
Probably we should think about the community and put in each chain element pkg/ README.md file with clarification about chain element to avoid confusion and questions "what this thing doing?".

**Comment by edwarnicke** [comment]
I think its probably a good idea :)  I've done it for some of them, probably would be helpful for others :)

**Comment by denis-tingaikin** [comment]
Currently we're adding README.md files optionally. For example for complex elements.
