### ISSUE TITLE
Rework prefixpool to work with using RoaringBitmap

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#389]
## Motivation

We've migrated prefix pool from mono repo to sdk https://github.com/networkservicemesh/sdk/tree/master/pkg/tools/prefixpool, but It looks like many things can be refactored and simplified with using this library:
https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/ipam/point2pointipam/server.go#L31

**Comment by denis-tingaikin** [comment]
@remingu Do you have any update on this?

**Comment by remingu** [comment]
@denis-tingaikin :
yes, have to push the code.  - will do asap. quite under some load atm. sorry

**Comment by edwarnicke** [comment]
@remingu Any progress? :)

**Comment by haiodo** [comment]
@remingu Any progress?
