### ISSUE TITLE
Create authorization registry chain elements.

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/sdk#47]
This is a followup for after #45.

We will also need authorization chain elements for connection.MonitorNetworkServiceServer and connection.MonitorNetworkServiceClient.

Please put them in the pkg/registry/common/ subdir

**Comment by denis-tingaikin** [comment]
@edwarnicke This is looking good to go. Can we schedule this for 1.4.0?

**Comment by denis-tingaikin** [comment]
Done by https://github.com/networkservicemesh/sdk/pull/1366
