### ISSUE TITLE
[Question] Should we add CodeQL action on ci?

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#498]
## Description
This action runs GitHub's industry-leading static analysis engine, CodeQL, against a repository's source code to find security vulnerabilities. It then automatically uploads the results to GitHub so they can be displayed in the repository's security tab. CodeQL runs an extensible set of queries, which have been developed by the community and the GitHub Security Lab to find common vulnerabilities in your code.

https://github.com/github/codeql-action

**Comment by denis-tingajkin** [comment]
@edwarnicke , @fkautz , @haiodo cc

**Comment by edwarnicke** [comment]
@denis-tingajkin  I've added it to api, sdk, sdk-vppagent, cmd-forwarder-vppagent :)

**Comment by denis-tingajkin** [comment]
@edwarnicke it was fast :)

**Comment by edwarnicke** [comment]
Its going to get really interesting next Sunday... currently, its just running on PRs and so looking for sec issues in delta changes... weekly it runs across the whole code base on Sundays (if I'm reading the job config correctly)

**Comment by denis-tingajkin** [comment]
@edwarnicke also I'm not sure about autobuild action. Do we need to use something like `go build ./...` instead of autobuild?

**Comment by denis-tingajkin** [comment]
Added by @edwarnicke
