### ISSUE TITLE
NSMgr doesn't handle MonitorConnectionServer

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#503]
## Description

On try to request any methods of MonitorConnectionServer related to nsmgr throws err by heal client: `unknown service connection.MonitorConnection`

## Problem

During testing I found that the heal chain element could fail testing via using real chains + grpc because of nsmgr is not implemented MonitorConnectionServer

## Potential solution

Register MonitorConnectionServer for nsmgr

**Comment by denis-tingajkin** [comment]
Actually, it is done https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/chains/endpoint/server.go#L68

**Comment by edwarnicke** [comment]
@haiodo @denis-tingajkin Is NSMgr not using chain/endpoint as its base?

**Comment by denis-tingajkin** [comment]
@edwarnicke nsmgr is using `chain/endpoint as its base` but for some reason, nsmgr doesn't register monitor service as well.

**Comment by edwarnicke** [comment]
That's super weird... I suspect *that* is the right place to fix it.

**Comment by edwarnicke** [comment]
OK... this should be registering a Monitor Service:

https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/chains/endpoint/server.go#L78

**Comment by denis-tingajkin** [comment]
Oops! I've locally checked and the root cause was in `nsmgr-proxy`. `nsmgr` is correctly registering monitor service.

**Comment by edwarnicke** [comment]
Good to know :)  I was a little concerned I'd screwed something up there :)
