### ISSUE TITLE
OPA should support multiple tokens in the chain

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/sdk#51]
OPA currently only reasons on a single token in the chain. It will be useful to have OPA support multiple tokens so that it can reason about elements deeper in the chain.

Context: https://github.com/networkservicemesh/sdk/pull/40#discussion_r369232544

**Comment by denis-tingaikin** [comment]
@fkautz Currently we have a few policies that are using multi tokens :

1. https://github.com/networkservicemesh/sdk/blob/main/pkg/tools/opa/policies/tokens_chained.rego
2. https://github.com/networkservicemesh/sdk/blob/main/pkg/tools/opa/policies/tokens_expired.rego

Let me know if you have something other in mind and then we can reopen this issue :)
