### ISSUE TITLE
Extract connectClient mechanism translation logic

### ISSUE THREAD

**Issue by xzfc** [networkservicemesh/sdk#552]
Currently, `connectClient` is used to translate `Connection.Mechanism` between incoming server connection and outgoing client connection:
https://github.com/networkservicemesh/sdk/blob/fbf9869cd4413a8be38f89b93220f10835a8fcf1/pkg/networkservice/common/connect/client.go#L47-L51

This behavior is required by `nsmgr` which uses `connect`: https://github.com/networkservicemesh/sdk/blob/fbf9869cd4413a8be38f89b93220f10835a8fcf1/pkg/networkservice/chains/nsmgr/server.go#L113

However, it is not required by `nsmgrproxy` which uses `connect` too:
https://github.com/networkservicemesh/sdk/blob/fbf9869cd4413a8be38f89b93220f10835a8fcf1/pkg/networkservice/chains/nsmgrproxy/server.go#L44

We need to extract mechanism translation logic from `connectClient` into a new chain element and embed it into `nsmgr` chain. Also, we may hide `connect.NewClient` as it becomes an implementation detail.

**Comment by edwarnicke** [comment]
> We need to extract mechanism translation logic from connectClient into a new chain element and embed it into nsmgr chain.

Question, would it might also be useful to allow for an option (preferably a With style option) to provide a function for the connection translation required by particular use?

**Comment by xzfc** [comment]
Ok, let's list translation use-cases:
* `Connection.Mechanism`: this issue.
* `Connection.Id`: required in the past, but no longer needed, as you said in https://github.com/networkservicemesh/sdk/pull/525#discussion_r505650097.

Do we have any other use-cases for this?

**Comment by edwarnicke** [comment]
> Ok, let's list translation use-cases:
> 
> * `Connection.Mechanism`: this issue.
> * `Connection.Id`: required in the past, but no longer needed, as you said in [#525 (comment)](https://github.com/networkservicemesh/sdk/pull/525#discussion_r505650097).
> 
> Do we have any other use-cases for this?

Those capture the two currently on the table yes.  I could imagine other aspects of the clientConnection (labels for example) being selectively copied to the serverConnection (thus my suggestion for a relatively genericizable With* Option for this).

**Comment by xzfc** [comment]
I think we may make it configurable later if such a requirement arises.

But currently, it is intended to be used in only one place (`nsmgr`) and only to translate Mechanisms, so we may make it unconfigurable, for simplicity.

**Comment by edwarnicke** [comment]
@xzfc Question... if the nsmgr and the forwarders have different needs around this, and its not configurable, how are we going to be able to get both their desired behavior?

**Comment by xzfc** [comment]
We would either put or don't put the new chain element into the `connect` chain (e.g., [here](https://github.com/networkservicemesh/sdk-vppagent/blob/687e3cc23267792a8ff9e60fa6d38e81a9192513/pkg/networkservice/chains/xconnectns/server.go#L94-L102) or [here](https://github.com/networkservicemesh/sdk/blob/fbf9869cd4413a8be38f89b93220f10835a8fcf1/pkg/networkservice/chains/nsmgr/server.go#L116-L117)) based on whether this NSE wants to translate mechanisms or not.
