### ISSUE TITLE
Investigate OpenTelemetry and provide a spec document of integration to NSM

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#569]
We are going to add support for OpenTelemetry. Currently, we need to investigate OpenTelemetry and add a plan of integrating it into NSM infrastructure.

To complete this issue should be provided a formulated specification document with all possible integration options.

Examples of specs:

https://github.com/networkservicemesh/networkservicemesh/issues?q=is%3Aissue+is%3Aopen+Spec

**Comment by tigrulya-exe** [comment]
Draft spec: https://docs.google.com/document/d/1ZOCHaq33O2I4xVOmwpA7MgsBq8uBCO-eSp4HE7brT3o/edit#
