### ISSUE TITLE
NSMgr should pass Close() calls

### ISSUE THREAD

**Issue by xzfc** [networkservicemesh/sdk#570]
Currently, NSMgr ignores incoming NetworkService `Close()` calls so that the corresponding NSE never receives them. More precisely, it is ignored by [discover] which is a part of NSMgr chain.

[discover]: https://github.com/networkservicemesh/sdk/blob/3b08d97e38650d6e85de383b395431a08c99a9eb/pkg/networkservice/common/discover/server.go#L103-L105

Related PR that introduced this behavior: https://github.com/networkservicemesh/sdk/pull/263.

To-do:
* [x] Fix `discoverServer` #571
* [ ] Refactor NSMgr sandbox tests, see https://github.com/networkservicemesh/sdk/pull/571#discussion_r518904845. Refactored tests should check that `Close()` works.
* [ ] Ensure that `Close()` works in a pass-trough scenario. Current status: `healClient` crashes. https://github.com/xzfc/networkservicemesh-sdk/commit/bb1e979bb0adff007a5c4e2d28f67fac1220446a

**Comment by xzfc** [comment]
Reopening as there are unfinished to-dos.

**Comment by denis-tingaikin** [comment]
The problem is resolved. Currently we have tests that covers closes and unregisters: 
https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/nsmgr/heal_test.go#L283-L289
