### ISSUE TITLE
Define and implement example/test OPA use cases.

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/sdk#58]
Initial OPA implementation is currently in the repo with a simple use case.

1. Define example use cases that we want to cover with OPA
2. For each use case, attempt to implement the policy. Document the results and gaps.
3. For each use case where a gap, expand OPA support.

**Comment by edwarnicke** [comment]
I'd think we probably want at least:

1)  Policy that checks to make sure the *last* token in the path matches the incoming TLS identity
2) Policy that lets you decide whether or not to admit based on the last token in the path
3)  Policy that lets you decide whether or not to admit based on any or all of the tokens in the path
4)  Policy that lets you decide whether to admit based on path information plus other information in the request (like the labels on the request).

**Comment by fkautz** [comment]
The idea is to expand on the current implementation where the authorize package is locally resolving and enforcing policy. Once we are happy with where we are at, we can discuss whether we should implement other models such as OPA in its own separate micro service.

**Comment by lobkovilya** [comment]
I thought of policy like something that accept identity (SPIFFE ID in our case) and decide whether Request allowed with such identity or not. And I thought that feature is mostly for implementing NSEs. 
Maybe we can do something like RBAC in k8s. User can deploy configmap with permissions or restrictions - which NSC's SPIFFE IDs have access to particular NSEs and which are not. And we will implement kind of "controller" that listens changes of the configmap and propagates policies on NSEs

**Comment by edwarnicke** [comment]
@lobkovilya I don't think we want to complicate things... what you really need is the information you might need to make the decision.  Everything else goes into the policy.  To make a decision we need:

The request (which includes the spiffe tokens, and from which spiffe ideas can be extracted in REGO)

The TLS information about the context.

Everything else can go into the REGO policy itself given that.
