### ISSUE TITLE
onHeal should be a function

### ISSUE THREAD

**Issue by xzfc** [networkservicemesh/sdk#582]
## Current design

The argument `onHeal` is a pointer to the interface, i.e. basically a double-pointer. It is intended to let `onHeal` to point to not yet created chain element, as described in the [heal.NewClient documentation](https://github.com/networkservicemesh/sdk/blob/4a6442d84a9b9fb4b702c5031c22776e0c919637/pkg/networkservice/common/heal/client.go#L49-L58). Additionally, `addressof` package is provided to deal with pointers to an interface.

Pros of the current design:
* It lets us pass the beginning of the chain to `heal`.
* `addressof` lets us take an address of an adapted server without introducing a temporary variable: `addressof.NetworkServiceClient(adapters.NewServerToClient(…))`.

Cons of the current design:
* The double-pointer API doesn't feel very clean.
* Issues like https://github.com/networkservicemesh/sdk/pull/581, https://github.com/networkservicemesh/sdk/issues/534#issuecomment-709687956.

## Proposal
Let `onHeal` be a function of a new type `HealFunc`. The `heal` is not intended to call `onHeal.Close`, so we could just extract `Request()` from `NetworkServiceClient` interface.

```go
type HealFunc func(context.Context, *networkservice.NetworkServiceRequest, opts ...grpc.CallOption) (*networkservice.Connection, error)
// It would be convenient to pass the Request method:
heal.NewClient(ctx, monitor, rv.Request)
```

Alternatively, it may have a simpler signature, like this:
```go
type HealFunc func(context.Context, *networkservice.NetworkServiceRequest) error
```

**Comment by edwarnicke** [comment]
This is a good idea... question though... what would this look like in the client chain?

Ed

**Comment by xzfc** [comment]
[Nsmgr connect chain](https://github.com/networkservicemesh/sdk/blob/74cd5de11f63eac6159c94e33ea6cde0022da9a6/pkg/networkservice/chains/nsmgr/server.go#L118-L124) could be rewritten as

```diff
 connect.NewServer(
 	ctx,
 	client.NewClientFactory(nsmRegistration.Name,
+		func(ctx context.Context, request *networkservice.NetworkServiceRequest, option ...grpc.CallOption) (*networkservice.Connection, error) {
+			return rv.Request(ctx, request)
+		},
 		tokenGenerator,
 	),
 	clientDialOptions...),
```

Or more concisely with a helper function:

```diff
 connect.NewServer(
 	ctx,
 	client.NewClientFactory(nsmRegistration.Name,
+		heal.AdaptServer(&rv),
 		tokenGenerator,
 	),
 	clientDialOptions...),
```

**Comment by denis-tingajkin** [comment]
> Or more concisely with a helper function:

I do not think that we should put adapt logic to `heal` pkg.

**Comment by xzfc** [comment]
I thought it is appropriate to put one or two commonly used helpers into the same package where the type `HealFunc` is defined. (see the updated issue description)

Like [`opa/policy.go`] provides some helpers for `CheckAccessFunc` and `AuthorizationPolicy`.

[`opa/policy.go`]: https://github.com/networkservicemesh/sdk/blob/4a6442d84a9b9fb4b702c5031c22776e0c919637/pkg/tools/opa/policy.go

**Comment by denis-tingaikin** [comment]
@edwarnicke , @glazychev-art Is the issue make sense? Can we close this one?

**Comment by edwarnicke** [comment]
I think onHeal is gone at this point... isn't it?

**Comment by glazychev-art** [comment]
I agree. Let's close this issue.
