### ISSUE TITLE
Spec: OpenTelemetry Integration

### ISSUE THREAD

**Issue by tigrulya-exe** [networkservicemesh/sdk#584]
We are going to add support for OpenTelemetry. We've investigated OpenTelemetry and added a possible options of integrating it into NSM infrastructure.

Now we need to choose the most suitable OpenTelemetry integration option of those suggested in the [spec](https://docs.google.com/document/d/1ZOCHaq33O2I4xVOmwpA7MgsBq8uBCO-eSp4HE7brT3o/edit?usp=sharing).

This issue was created for discussions.

**Comment by denis-tingajkin** [comment]
@edwarnicke Could you take a look?

**Comment by denis-tingajkin** [comment]
@edwarnicke, @fkautz Could you take a look?

**Comment by glazychev-art** [comment]
In implementation we discovered goroutine leakage issues. They are related to the opentelemetry side.
Issues were created describing this problems:
https://github.com/open-telemetry/opentelemetry-go-contrib/issues/501
https://github.com/open-telemetry/opentelemetry-go-contrib/issues/502

They block further work on this issue. 
The [Draft PR](https://github.com/networkservicemesh/sdk/pull/628) was created.

**Comment by denis-tingaikin** [comment]
Few things about this.

**Comment by edwarnicke** [comment]
@glazychev-art Are we still seeing go routine leaks?

**Comment by denis-tingaikin** [comment]
All PRs merged. CI passed on kind https://github.com/networkservicemesh/integration-k8s-kind/pull/555

So closing.
