### ISSUE TITLE
Discovery chain element should try to wait NS and NSE on request

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/sdk#593]
## Problem statement

We should not use wait for the state in the tests. So in this case we should allow starting NSE and NSE in parallel. To achieve this we can add waiting for NS and NSE in the discovery chain element.

## Current discovery behavior
1. Request NS
2. Check NS response
2.1. If NS is existed then ok go next
2.2. If NS is not existed then return err

## Potential fix for discovery behavior
1. Request NS
2. Check NS response
2.1. If NS exists and it is suitable then ok go next
2.2. If NS is not existed then try  to watch while ctx is not done

**Comment by haiodo** [comment]
@denis-tingajkin  could we recv from registry using find until we receive a required endpoint or context timeout?

**Comment by edwarnicke** [comment]
> @denis-tingajkin could we recv from registry using find until we receive a required endpoint or context timeout?

That sounds like a winning approach: be event driven, not timer driven :)

**Comment by denis-tingajkin** [comment]
Yes, events sound good, will try to go with this direction
