### ISSUE TITLE
Time-sensitive tests are flaky on macOS CI

### ISSUE THREAD

**Issue by xzfc** [networkservicemesh/sdk#613]
Consider this simple code:
```go
start := time.Now()
time.AfterFunc(15 * time.Millisecond, func() {
	// Compare `time.Now()` and `start.Add(15 * time.Millisecond)`
})
```
While `time.AfterFunc` doesn't guarantee that the function would be started exactly in 15ms, time lags on macOS Github Actions runner are far more common than on the Ubuntu runner. The same issue applies to the Windows runner, but to a lesser extent.

See this [test code](https://github.com/xzfc/networkservicemesh-sdk/blob/01ab7c6bd310301ebaf3359f3b11b03826d5f98e/pkg/networkservice/common/refresh/timers_test.go) running on [github actions](https://github.com/xzfc/networkservicemesh-sdk/runs/1496515757?check_suite_focus=true): on macOS, 1/3 of timers are late by at least 1ms, up to 61ms(!). During `refresh` chain element unit testing, I have seen 130ms lags in similar cases.

This issue affects sandbox tests as it rearranges the execution order of timer-based chain elements (`refresh`, `timeout`).

Disabled time-sensitive flaky tests would be linked to this issue.

**Comment by edwarnicke** [comment]
As a general rule, the answer is to be even driven rather than time driven.  That said, sometimes you really do just need to wait to see if the event you are expecting happens at all in testing, so sometimes timers are unavoidable.

**Comment by denis-tingaikin** [comment]
Fixed with `clock`.
