### ISSUE TITLE
Unify logging and tracing API

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#614]
## Problem statement

Currently, we have three ways to logging staff into the project.

1. Logging via  `log` pkg. https://github.com/networkservicemesh/sdk/tree/master/pkg/tools/log
2. Logging via `trace` pkg. https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/core/trace/context.go#L51
3. Logging via `spanhelper` pkg. https://github.com/networkservicemesh/sdk/tree/master/pkg/tools/spanhelper

The count of logging APIs could confuse the developers. It is also could be not clear what the package should be used in the concrete case. Besides our logging could be not dependent on a concrete logging provider(logurs).

## Solution

Implement and merge the logging logic of these packages into one.

The result of pkg should export the next API:

```go
package TODO

type Logger interface{
    Info(v ...interface{})
    Infof(format string, v ...interface{})
    Warn(v ...interface{})
    Warnf(format string, v ...interface{})
    Error(v ...interface{})
    Errorf(format string, v ...interface{})
    Fatal(v ...interface{})
    Fatalf(format string, v ...interface{})
  
    WithField(k, v interface{}) Logger
}

func Log(ctx context.Context) Logger {
    //TODO: implement the code here
}
```

**Comment by denis-tingajkin** [comment]
@edwarnicke we are thinking to solve this. Do you mind the suggested approach?
