### ISSUE TITLE
updatetoken client generates tokens using server authinfo in connect chain

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#702]
## Issue

The issue is related to two problems:

1. When server `connect` uses `updatetoken` client then the client using the `connect` server's` authinfo.

Look at
https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/common/updatetoken/client.go#L45
https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/chains/client/client.go#L71
https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/utils/inject/injectpeer/client.go#L83

As you can see `injectpeer ` sets a peer on backward when to generate the token it should be done before calling next.

2. NSC can not set [aud](https://tools.ietf.org/html/rfc7519#section-4.1.3) in its JWT because at first NSC should resolve the service name.

## Solutions

Currently, we have two solutions for this issue:

1. Create `authorize` ns client chain element that will do handshake via
https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go#L144 in this case updatetoken will correctly generate tokens.

2. Somehow match endpoint in the registry to spiffieID and use it in `aud`.

**Comment by denis-tingaikin** [comment]
@edwarnicke Can we go with option1? Please share your thoughts.

**Comment by edwarnicke** [comment]
I like option 1 as an approach :)

**Comment by haiodo** [comment]
A good idea will be to use peer credentials and or Certificate with SpiffieID specified.
