### ISSUE TITLE
Connect server doesn't handle GRPC connection error

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#704]
# Intro
If GRPC connection failes, `connect` server does nothing to make a new GRPC connection, so all subsequent requests will fail with GRPC error until `discover` find a new URL.
# Issue
If remote server restarts, healing can't recover connection without selecting a new server.
# Solution
#703

If `connect` server receives a GRPC error from client request, it deletes it. Subsequent request to this URL:
* with the same connection ID - will create a new client and continue working after 1 error received.
* with different connection ID - will receive a GRPC error, because `connInfo` still refers to the old client but will replace old client with a new one on further requests.

**Comment by edwarnicke** [comment]
This feels like an issue around the connection of the monitor in the client to the monitor in the server.

Just cleaning up in the connect client won't work properly  because there may be things to cleanup in the server chain elements.

**Comment by denis-tingaikin** [comment]
@edwarnicke I'm not quite following this.

For example, 

`connect` server has 1000 clients with the same URL to some server. 
It means that we have 1000 refs in refcount map.
After some time the server died.

Question: Could you explain how you see the closing of these clients?

**Comment by edwarnicke** [comment]
How do you reliably tell that the Endpoint is dead, instead of there being some other problem local to the particular Connection being processed?

**Comment by denis-tingaikin** [comment]
grpc returns error with [status code](https://pkg.go.dev/google.golang.org/grpc@v1.35.0/codes#Code) if connection died. Is it enough to handle that endpoint is dead?

**Comment by edwarnicke** [comment]
None of these codes tell you anything about the status of the Client... just the request.  Even in #703 we are [looking at](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L39) the [codes.Canceled](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L39) tells you nothing about the Client status... just that that *particular* request was Canceled for some reason... the client could be fine, or it could not.

So lets talk through this a bit, consider scenario "Remote Server dies and doesn't come back".
