### ISSUE TITLE
Endpoint doesn't handle NS unregister

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#712]
# Intro
Endpoint has 2 registry chains: NS, NSE. Both chains has expire unregister logic on server side:
* NS - there are no more NSEs implementing such NS
* NSE - expiration time happens
To prevent NSE from unregistering, we have `refresh` chain element on client side, it should send `Register` updates to increase NSE expiration time. While it sends updates before `expire` fires on the server side, both NS, NSE wouldn't be unregistered.
# Issue
If NSE/network becomes laggy, `expire` can fire before `refresh` event reaches the server. In such case server unregisters both NS, NSE. After that, `refresh` events can register only NSE, but not NS and endpoint `main` doesn't get any information about that.

**Comment by denis-tingaikin** [comment]
NS expire has been removed
