### ISSUE TITLE
Endpoint registry chain doesn't handle GRPC connection failure

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#713]
# Issue
If GRPC connection fails, both NS, NSE endpoint registry chains become invalid.

**Comment by Bolodya1997** [comment]
**Use cases:**
1. Registry restarts - NSMgr reconnects and updates registration for all its Services, Endpoints.
2. NSMgr restarts - Endpoint reconnects and update registration for self Services, Endpoint.
3. Registry/NSMgr restarts - all watching Find requests still OK.

**Problems:**
1. NSMgr, Endpoint both pass to chain `grpc.ClientConnInterface` instead of URL, so it is impossible to heal connection from the chain.
2. Streaming Find will break on gRPC connection failure, heal chain element needs some solution to prevent passing this failure down to the Find requester.

**Solution (for both NS, NSE chains):**
Should be almost the same as for Endpoint:
![image](https://user-images.githubusercontent.com/20160689/119034454-89265f80-b9d8-11eb-89ce-06a64293dbea.png)
So for NSMgr:
![image](https://user-images.githubusercontent.com/20160689/119034834-094cc500-b9d9-11eb-872a-c3b402fb40bc.png)

1. Use connect server generating client instead of simple gRPC client.
2. Heal server should send error to the Find server only on restore error.

**Comment by Bolodya1997** [comment]
@edwarnicke 
Does it look OK to you?

**Comment by edwarnicke** [comment]
> 1. NSMgr, Endpoint both pass to chain grpc.ClientConnInterface instead of URL, so it is impossible to heal connection from the chain.

Which chain is grpc.ClientConnInterface being passed to?  Could you link to an example?

**Comment by Bolodya1997** [comment]
> Which chain is grpc.ClientConnInterface being passed to? Could you link to an example?

In every Registry chain:
1. Endpoint - https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/c3465e8bb30efa27301f81448b6dc5c0c643f701/main.go#L244
2. NSMgr - https://github.com/networkservicemesh/sdk/blob/a846774fcd8123db9e2a7c4af80cdd923787c1b9/pkg/networkservice/chains/nsmgr/server.go#L107

It is actually fixed on the `sdk` side and I am working on fixing it on `cmd-` sides.

**Comment by Bolodya1997** [comment]
Closed with #954 merged.
