### ISSUE TITLE
Endpoint doesn't handle the case when refresh is late

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#714]
# Intro
Registry generates new `nse.Name` for all newly registered NSEs and returns it back with the `Register` response. If `Register` comes with already existing `nse.Name` it means that it is a refresh `Register` event. When `Unregister` comes with already existing `nse.Name`, registry deletes it.
# Issue
If endpoint `refresh` NSE registry chain elements is late, `expire` deletes NSE on the server side. Subsequent `refresh` events register NSE as a new NSE with a new `nse.Name` and it doesn't matches `nse.Name` in the endpoint `main`. If endpoint wants to manually `Unregister` NSE, it will fail.

**Comment by denis-tingaikin** [comment]
Could you say more about used chain elements, steps to reproduce and so on?

**Comment by Bolodya1997** [comment]
Fixed with generating NSE name on the Endpoint side - https://github.com/networkservicemesh/sdk/pull/789.
