### ISSUE TITLE
Issue with swapping between Endpoint URL and NSMgr URL

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#770]
# Intro
When endpoint registers on NSMgr, NSMgr stores its URL locally and passes NSE registration with URL replaced to NSMgr URL in localbypass NSE server chain element.

```
Endpoint  -Register->  NSMgr    : { URL: nseURL }
NSMgr     -Register->  Registry : { URL: nsmgrURL }
```
When NSMgr needs to find the endpoint, localbypass replaces URL back:
```
NSMgr (localbypass)  <-Find-  Registry            : { URL: nsmgrURL }
NSMgr                <-Find-  NSMgr (localbypass) : { URL: nseURL }
```
localbypass can't store name -> URL mapping before passing NSE registration to the next, because it doesn't yet have name. So there is a moment in time when NSE is already stored in Registry but not yet exists in localbypass mappings.

# Issue
Sometimes we can get locally registered NSE with `{ URL: nsmgrURL }` from `Find`.

# Possible solutions

## Without changing api

`localbypass` can make `Register` event + refresh `Register` event and filter out from `Find` all endpoints with `nse.Url == NSMgr.Url` and not presented in the local mappings - #767.

## With changing api

Instead of single `nse.Url` field we can make `nse.Url`, `nse.NsmgrUrl` fields and don't make any substitutions on `Register`, `Unregister`, `Find`. We only need to select right URL and we can easy make it comparing `nse.NsmgrUrl` with our `NSMgr.Url`.

**Comment by denis-tingaikin** [comment]
@edwarnicke cc

**Comment by edwarnicke** [comment]
My understanding is that [memory](https://github.com/networkservicemesh/sdk/tree/master/pkg/registry/common/memory) acts as a pass through cache for lookup, meaning that it stores what comes in, and then calls the next chain element.

Could we not simply put a memory chain element along the path of the chain.  That would give us a local cache that has the inode urls for things that register locally.  When carrying out a Find, I feel like an ultrasimple chain element that drops the NSMgrs URL could be used downstream of that memory chain element to make sure locally we only get local resolution from the memory chain element.

Thoughts?

**Comment by Bolodya1997** [comment]
It looks like a solution.
Do we imagine case when some locally added NSE is getting update not from ourselves?

**Comment by Bolodya1997** [comment]
So now we have at least 2 solutions:
1. Store `name -> URL` mappings in `localbypass` and use double Register for new endpoints:
   ```
   localbypass(-) == localbypass without URL mapping for the Endpoint
   localbypass(+) == localbypass with URL mapping for the Endpoint

   -- Register (1) --

   Endpoint --(1)-> NSMgr [ -> localbypass(-) -> ] --(2)-> Registry
                    NSMgr [    localbypass(-) <- ] <-(3)-- Registry
                    NSMgr [    localbypass(+) -> ] --(4)-> Registry
   Endpoint <-(6)-- NSMgr [ <- localbypass(+) <- ] <-(5)-- Registry

   (1, 6)       nse.Url = Endpoint URL
   (2, 3, 4, 5) nse.Url = NSMgr URL

   -- Register (2) --

   Endpoint --(1)-> NSMgr [ -> localbypass(+) -> ] --(2)-> Registry
   Endpoint <-(4)-- NSMgr [ <- localbypass(+) <- ] <-(3)-- Registry

   (1, 4) nse.Url = Endpoint URL
   (2, 3) nse.Url = NSMgr URL

   -- Find (1) --

                    NSMgr [    localbypass(-) <- ] <-(1)-- Registry

   (1) nse.Url = NSMgr URL, nse.ExpirationTime.Seconds != -1

   -- Find (2) --

   Endpoint <-(2)-- NSMgr [ <- localbypass(-) <- ] <-(1)-- Registry

   (1, 2) nse.Url = NSMgr URL, nse.ExpirationTime.Seconds == -1

   -- Find (3) --

   Endpoint <-(2)-- NSMgr [ <- localbypass(+) <- ] <-(1)-- Registry

   (1) nse.Url = NSMgr URL
   (2) nse.Url = Endpoint URL

   -- Find (4) --

   Endpoint <-(2)-- NSMgr [ <- localbypass( ) <- ] <-(1)-- Registry

   (1, 2) nse.Url = other URL
   ```
   **Pros:**
   * for every locally registered endpoint we are storing only `name -> URL` mapping
   
   **Cons**:
   * we need second Register to avoid filtering initial Register event in `Find (1)` if there is a watching Find during the `Register (1)`

2. Use `memory` as a local cache:
   ```
   --- Register ---

   Endpoint --(1)-> NSMgr [ -> memory -> localbypass -> ] --(2)-> Registry
   Endpoint <-(4)-- NSMgr [ <- memory <- localbypass <- ] <-(3)-- Registry

   (1, 4) nse.Url = Endpoint URL
   (2, 3) nse.Url = NSMgr URL

   -- Find (1) --

                    NSMgr [              localbypass <- ] <-(1)-- Registry

   (1) nse.Url = NSMgr URL

   -- Find (2) --

   Endpoint <-(1)-- NSMgr [ <- memory                   ]

   (1) nse.Url = Endpoint URL

   -- Find (3) --

   Endpoint <-(2)-- NSMgr [ <- memory <- localbypass <- ] <-(1)-- Registry

   (1, 2) nse.Url = other URL
   ```
   **Pros:**
   * there is no need for the additional Register

   **Cons:**
   * for every locally registered endpoint we are storing all its registration data

**Comment by denis-tingaikin** [comment]
@Bolodya1997 Why we can just serialize all registers, unregisters, finds by nse.Name.

**Comment by Bolodya1997** [comment]
> @Bolodya1997 Why we can just serialize all registers, unregisters, finds by nse.Name.

It cannot solve this issue, because we doesn't have `nse.Name` to serialize by during the first Register for the endpoint.

**Comment by edwarnicke** [comment]
@Bolodya1997 Shouldn't the endpoint be providing an nse.Name for itself?

**Comment by Bolodya1997** [comment]
So we discussed a lot and the newest approach is the following -`nse.Name` should be generated on the Endpoint side with checks for the collisions on NSMgr, Registry.
```
Endpoint [ -> SetID -> ] -> NSMgr [ -> NameCheck -> Localbypass -> ] -> Registry [ -> NameCheck -> Memory ]
```
Collision is when we have the same `nse.Name` but different `nse.Url` -  in such case `NameCheck` returns some `DuplicateNameError` error and `SetID` tries again with another generated `nse.Name`.

Such approach should make registry chains less complicated because at the moment we have such logic:
```
Register(nse Endpoint) {
   1. try to do something with nse.Name (what if it is a Refresh Register)
   reg = next.Register(nse)
   2. now we can do something with reg.Name
}
```
so the first hop in the chain who gets Endpoint registered is the last hop and it can result in some funny issues like this.

After we start generating `nse.Name` on the Endpoint side there becomes possible:
```
Register(nse Endpoint) {
   1. do something with nse.Name
   return next.Register(nse)
```
