### ISSUE TITLE
Use go:embed from go 1.16 to store OPA policies in separate files

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#781]
## Motivation

With go 1.16 we can use files from the project. Look at https://golang.org/pkg/embed/

Currently, OPA policies are storing as strings. So now we can move them into separate files to make it easy to find/edit and to reduce the complexity of the go files.

**Comment by denis-tingaikin** [comment]
@edwarnicke Also https://golang.org/pkg/embed/ can be used for vpp configs :)

**Comment by edwarnicke** [comment]
@denis-tingaikin Yes :)
