### ISSUE TITLE
Use IP payload for all registering NSs that have not set payload

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#792]
## Description

We need to cover a case when NS registering without `payload` field.

In this case, we can reject the request, or keep in mind that the default value is `IP`.

I think option 2 is more tolerant. 

## Implementation details

1. Add new registry pkg for checking payloads: I.e. create a new server struct and implement https://github.com/networkservicemesh/api/blob/master/pkg/api/registry/registry.proto#L43-L47
2. Add units tets for the pkg by analogy with other registry pkgs
3. Add new chain into https://github.com/networkservicemesh/sdk/blob/master/pkg/registry/chains/memory/server.go#L53
4. Add or modify existing sandbox tests to check that it is wroking: https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/chains/nsmgr/server_test.go#L113

**Comment by edwarnicke** [comment]
I think IP is probably a more appropriate default payload for an NS that doesn't specify one than ethernet.  While there *are* use cases for Ethernet, most are for IP.

**Comment by denis-tingaikin** [comment]
OK, that's good to know. Will do IP by default 👍
