### ISSUE TITLE
Propose the issue template for NSM repositories

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#807]
## Description

To achieve the best communication with the community or with new members we can consider adding the issue template for our repositories.

## Implementation details

1. See at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
2. Propose the issue template in this issue.
3. Contribute the issue template into the repository.

**Comment by DVEfremov** [comment]
An Option for Issue template: 

Env description: 
Step to reproduce: 
Actual Result:
Expected Result: 

For example: 
**Env description:** 
OS: Ubuntu 18.x, 

**Step to reproduce:** 
1. Create ...
2. ...

**Actual Result:**
See the error "bla bla .." in the log

**Expected Result:** 
No error.

**Comment by denis-tingaikin** [comment]
@DVEfremov 
This looks interesting.

You also could take a look at our issue template from the monorepo:
https://github.com/networkservicemesh/networkservicemesh/issues/2241
https://github.com/networkservicemesh/networkservicemesh/issues/2240
https://github.com/networkservicemesh/networkservicemesh/issues/2238
https://github.com/networkservicemesh/networkservicemesh/issues/2231

**Comment by edwarnicke** [comment]
It's also worth noting that some issues are improvements or features rather than just bugs :)

**Comment by denis-tingaikin** [comment]
@DVEfremov 

Here are our templates from monorepo:
1. https://github.com/networkservicemesh/networkservicemesh/blob/master/.github/ISSUE_TEMPLATE.md
2. https://github.com/networkservicemesh/networkservicemesh/blob/master/.github/PULL_REQUEST_TEMPLATE.md
3. https://github.com/networkservicemesh/networkservicemesh/tree/master/.github/ISSUE_TEMPLATE
4.

**Comment by denis-tingaikin** [comment]
> It's also worth noting that some issues are improvements or features rather than just bugs :)

I would be suggesting starting with these templates:
1. Feature
2. Bug
3. Question
