### ISSUE TITLE
Decompose 'Interdomain support' and provide estimation for each task

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#816]
## Description
The result of this issue should be a list of issues with estimations related to _Interdomain support_.

## Estimation:
 ~1h

**Comment by denis-tingaikin** [comment]
Plan:

1. Check current interdomain realization and suggest improvements `~2-3h` 
2. Create issues and apply fixes for step1. `~2d`
3. Add a separate repository for interdomain testing `~1h`
4. Implement the first version of interdomain CI testing in the new repository from step . `~2h`
5. Add interdomain tests into deployments k8s + testing. `~7d`

**Comment by Bolodya1997** [comment]
Issue related to interdomain: https://github.com/networkservicemesh/sdk/issues/827

**Comment by denis-tingaikin** [comment]
@Bolodya1997 It is good that we have already reported issue :) 
So I plan to consider #827 during step2.

**Comment by denis-tingaikin** [comment]
Decomposition is done. Progress will be tracking in https://github.com/networkservicemesh/sdk/issues/854
