### ISSUE TITLE
Decompose 'Continuous Upgrade Testing ' and provide estimation for each task

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#818]
## Description
Testing the impact of NSM upgrades to running the NSM system. The result of this issue is a list of tasks with the estimation needed to complete _Continuous Upgrade Testing_.

**Comment by denis-tingaikin** [comment]
Currently, I don't quite follow this direction.

@edwarnicke , @fkautz Could you provide an example for 'Continuous Upgrade Testing'?

**Comment by edwarnicke** [comment]
The idea is to have a running system, update it with an 'upgrade' to the NSM components (not NSCs or NSEs) and see functionality continue.

**Comment by denis-tingaikin** [comment]
@edwarnicke I see the next example:

Steps to reproduce:
1. Deploy new nsmgr, forwarder, registry (for example that using nsm/api/v2)
2. Deploy old NSC, NSE (for example that using nsm/api/v1)

Actual: NSC should get connectivity, NSE should be registered.

Am I get it correctly?

**Comment by denis-tingaikin** [comment]
Spec is done. The progress will be posted in https://github.com/networkservicemesh/sdk/issues/859
