### ISSUE TITLE
Decompose 'Destructive Chaos Testing' and provide estimation time for each task

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#823]
## Description
The result of this issue should be a list of issues with approximate estimations related to _Destructive Chaos Testing_.
## Raw estimation
`80d`

**Comment by Bolodya1997** [comment]
## Sandbox testing

**1 death cases:**
1. Local NSMgr:
   * **restored:**
      1. The same Forwarder selected.
      2. Another Forwarder selected.
2. Local Forwarder:
   * **restored**
   * **died**
3. Local Endpoint:
   * **restored**
   * **died:**
      1. A new local Endpoint selected.
      2. A new remote Endpoint selected.
4. Remote NSMgr:
   * **restored:**
      1. The same remote Forwarder selected.
      2. Another remote Forwarder selected.
   * **died:**
      1. A new local Endpoint selected.
      2. A new remote Endpoint selected.
5. Remote Forwarder:
   * **restored**
   * **died**
6. Remote Endpoint:
   * **restored**
   * **died:**
      1. A new local Endpoint selected.
      2. A new remote Endpoint selected.

**2 death cases:**
1. Local NSMgr(r) +
   1. Local Endpoint(r/d)
   2. Remote NSMgr(r/d)
   3. Remote Forwarder(r/d)
   4. Remote Endpoint(d)
2. Local Forwarder(r) +
   1. Local Endpoint(r/d)
   2. Remote NSMgr(r/d)
3. Remote NSMgr(r) +
   1. Remote Endpoint(r/d)
4. Remote Forwarder(r) +
   1. Remote Endpoint(r/d)

**3 death cases:**
1. Local NSMgr(r) +
   1. Remote NSMgr(r) + Remote Endpoint(r)
   2. Remote Forwarder(r) + Remote Endpoint(r)
2. Local Forwarder(r) +
   1. Remote NSMgr(r) + Remote Endpoint(r)
   2. Remote Forwarder(r) + Remote Endpoint(r)

**Should be tested:**
1. Shutdown becomes when hop:
   1. doesn't pass any Request/Close.
   2. passes Request.
   3. passes Close.
2. If case includes selecting another Forwarder/Endpoint, during the healing should be selected:
   1. the same mechanism.
   2. another mechanism.

## Integration testing

Since we are using unix sockets and sendfd/recvfd, every Forwarder/Endpoint restart is equal to its death, because after restart there will be a new URL. So some of the mixed tests wouldn't make any sense for the unit testing.

**Test cases:**
1. Local NSMgr(r) +
   1. none
   2. Local Endpoint(d)
   3. Remote NSMgr(r/d)
   4. Remote Forwarder(d)
   5. Remote Endpoint(d)
2. Local Forwarder(r/d)
3. Local Endpoint(r/d)
4. Remote NSMgr(r/d) +
   1. none
   2. Remote Endpoint(d)
5. Remote Forwarder(r/d)
6. Remote Endpoint(r/d)

**We can additionally add some multideath cases for integration for some random hops like:**
1. Local NSMgr(r) + Local Endpoint(d) + Remote NSMgr(r)
2. Local Forwarder(d) + Remote Forwarder(r) + Remote Endpoint(r)
3. ...

**Comment by Bolodya1997** [comment]
Currently all of this is blocked by:
* heal rework - https://github.com/networkservicemesh/sdk/issues/797
* issue related to the connect - https://github.com/networkservicemesh/sdk/issues/808

Sandbox testing is additionally blocked by:
* clock in sandbox (to manage correctly refresh/timeout scenarios) - https://github.com/networkservicemesh/sdk/issues/764

Integration _Local/Remote NSMgr(r)_ cases are additionally blocked by:
* no healing in registry chain (Forwarder/Endpoint wouldn't reregister to the restored NSMgr) - https://github.com/networkservicemesh/sdk/issues/713

**Comment by Bolodya1997** [comment]
We will additionally need some test plan for testing interdomain cases when it will be ready.

**Comment by Bolodya1997** [comment]
@edwarnicke cc

**Comment by edwarnicke** [comment]
@Bolodya1997 This looks good! :)
