### ISSUE TITLE
Naming convention branches and commits

### ISSUE THREAD

**Issue by DVEfremov** [networkservicemesh/sdk#833]
Naming convention branches and commits:

# for git branches: 
## for bugs: bug/\<issue number\>-\<couple-of-words-optional\>
Example: 
bug/issue-807-hadle-reconnection

## for planned features from SOW: 
Example: feature/issue-807-item1

## for a really quick fix (without issue in GitHub, but should be 
very rarely used): 
Example: qfix/fix-wording

# for git commits: 
issue#\<issue number\> \<Short description of changes\>
Example: issue #832 Handle reconnection

**Comment by denis-tingaikin** [comment]
@d-uzlov , @Bolodya1997 , @glazychev-art , @edwarnicke  cc

**Comment by denis-tingaikin** [comment]
@DVEfremov Should we also conder PR naming?

**Comment by denis-tingaikin** [comment]
@DVEfremov What do you think about these conventions https://www.conventionalcommits.org/en/v1.0.0/?

**Comment by edwarnicke** [comment]
@DVEfremov I'm a little confused... upstream we use the standard open source convention of all development happening on main (or master) and only pulling short lived throttles for releases... not using feature branches.

Of course locally folks have their own branches that eventually turn into PRs... but I don't quite yet understand why a naming convention for folks local branches matters all that much... they don't wind up in the upstream repo as branches.

**Comment by DVEfremov** [comment]
@edwarnicke 
The point was to automatically link PRs to git hubs issues. As I can see the team already links PRs mentioning issues number in PR description in PR names so it working fina already. 

Also creating my own branch for PR just noticed there some branches named without and specific format and suggested using some common branch naming format. 

I agree that looks unnecessary because we are creating a branch in our own forks and nobody will see it finally ;)

**Comment by edwarnicke** [comment]
@DVEfremov We can already do that with a simple #{{issue number}} commit message or PR comments, which seems much less invasive.

I *love* tying commits to issues... its a fantastic idea.  Just looking for the simplest way to do so :)

**Comment by DVEfremov** [comment]
@edwarnicke  
the simplest way to link commits/MR to issue could be a PR template ( I need to play around and propose a minimal version of the PR template)

**Comment by edwarnicke** [comment]
@DVEfremov PR templates are good generally :)
