### ISSUE TITLE
Floating interdomain support

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#853]
## Overview

Plan:

1. #816
2. Test floating intedromain scenario with registry-k8s as we test it with registry-memory: https://github.com/networkservicemesh/sdk/blob/master/pkg/registry/core/interdomain/interdomain_ns_test.go#L190,
https://github.com/networkservicemesh/sdk/blob/master/pkg/registry/core/interdomain/interdomain_nse_test.go#L200
5d.
3. Add floating interdomain tests into deployments k8s for { registry-k8s, registry-memory}: 4d
3.1. Test nsmgr request scenario with one domain.
3.2. Test nsmgr request scenario with two domains.
3.3. Test nsmgr request scenario with tree domains.

## Link to the Google Docs document

https://github.com/networkservicemesh/networkservicemesh/issues/1592

## References

https://github.com/networkservicemesh/sdk/issues/817

**Comment by denis-tingaikin** [comment]
@edwarnicke 
Note: at step 4 of Register actually nsmgr-proxy can know many registry-proxy that located at the cluster. It means we can do a permutation of registry-proxies and step4 as we do in interpose chain element.
It means we can have more than one proxy-registry implementation on the cluster that makes NSM more flexible in my mind :)

**Comment by denis-tingaikin** [comment]
>So if the NSMgr doesn't find the NSE in its local cache... it won't have the necessary information to contact the NSE. Meaning even if we did steps 14-17... it wouldn't do us any good :(

NSMgr could be run without cache. But the URL can be located in localbypass chain element. Note: this chain element stores only URLs.

**Comment by edwarnicke** [comment]
> > So if the NSMgr doesn't find the NSE in its local cache... it won't have the necessary information to contact the NSE. Meaning even if we did steps 14-17... it wouldn't do us any good :(
> 
> NSMgr could be run without cache. But the URL can be located in localbypass chain element. Note: this chain element stores only URLs. For this case steps 14-17 make sense.

Hmm... would it perhaps not be simpler to simply store the unaltered NSE registration (with inode:// url) in the cache and then do the translation on the way up to the registry?  In that case, would we need localbypass at all?  Localbypass is basically just a partial cache...

**Comment by edwarnicke** [comment]
> @edwarnicke Also I feel we need to implement a registry heal chain element to add possible to nse to re-register itself on nsmgr die :)

Correct me if I'm wrong, we have the API pieces for this, correct?  It basically just would involve the NSE Monitoring its own registration, and if its missing reregistering it?

**Comment by denis-tingaikin** [comment]
> Hmm... would it perhaps not be simpler to simply store the unaltered NSE registration (with inode:// url) in the cache and then do the translation on the way up to the registry? In that case, would we need localbypass at all? Localbypass is basically just a partial cache...

 I think it makes sense. Should we replace localbypass with the memory cache before starting this?

**Comment by denis-tingaikin** [comment]
>Correct me if I'm wrong, we have the API pieces for this, correct? It basically just would involve the NSE Monitoring its own registration, and if its missing reregistering it?

Mostly yes. Only one moment that we also need to create new cc to the server.
