### ISSUE TITLE
Interdomain support

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#854]
## Overview

See description in o the Google Docs document.

Plan:

- [X] 1. Check current interdomain realization and suggest improvements. I.e. find bugs and create issues. `~3d`

- [ ] 2. Apply fixes for step1. `1w`

- [ ] 3. Update all interdomain apps to the latest changes. `4h`
- [ ] 4. Add a separate repository for interdomain testing and implement the first version of interdomain CI testing in the new repository. `4d`
- [ ] 5. Add interdomain tests into deployments k8s + testing. `3d`

## Link to the Google Docs document

https://docs.google.com/document/d/1QjdJbYvzzsn6ARFq2iQcdBG9RN9m-Lx9kOq53sasnH8/edit#

## References

https://github.com/networkservicemesh/sdk/issues/816

**Comment by denis-tingaikin** [comment]
@edwarnicke Currently I'm fixing chain element to support this scheme in SDK
![New Interdomain](https://user-images.githubusercontent.com/49399980/117649602-ea208d00-b1b9-11eb-9e85-5d533df92a50.png)

Let me know if something is missed :)

**Comment by edwarnicke** [comment]
Looks about right, do you have line of site to what needs to be fixed yet?

**Comment by denis-tingaikin** [comment]
> do you have line of site to what needs to be fixed yet?

Currently, I have not.

I found two major issues in the monorepo implementation that already  fixed in the scheme https://github.com/networkservicemesh/sdk/issues/854#issuecomment-836558835

Issues:

1. In the monorepo implementation we do not include nsmgr-proxy. (to get remote node public ip/port we are using additional service what looks is not cool)
2. at step5 in monorepo we append the URL of remote nsmgr-proxy into NSE.Name field that also looks strange.

I mostly finished fixing this in SDK and soon plan to start test interdomain on kind clusters.

**Comment by edwarnicke** [comment]
> Currently, I have not.

That's fine.  I expect this to be an exploration :)
