### ISSUE TITLE
NSE Composition: Registry should be able to match labels from NSE label as from list of labels

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#871]
## Overview

Registry should be able to match labels from NSE label as from list of labels:
```
NSE-1:  label=one
NSE-2:  label=two
NSE-12: label=one,two

find:   label=one
result: { NSE-1, NSE-12 }

find:   label=two
result: { NSE-2, NSE-12 }
```

## References
* select NSEs from memory registry by query - https://github.com/networkservicemesh/sdk/blob/79914fd80cf93da45b0905efeaba468425b86839/pkg/registry/common/memory/nse_server.go#L111
* select NSEs from k8s registry by query - https://github.com/networkservicemesh/sdk-k8s/blob/c5dac67b50b69c78dedf559391d31ce464cd8932/pkg/registry/etcd/nse_server.go#L84
* corresponding method in `matchutils` - https://github.com/networkservicemesh/sdk/blob/79914fd80cf93da45b0905efeaba468425b86839/pkg/tools/matchutils/utils.go#L37

## Tests
1. Unit tests in `matchutils`.
2. Sandbox test (would be nice to create for both memory, k8s registries):
   1. add endpoint with list label (label=one,two)
   2. request NS with simple label (label=one)

**Comment by d-uzlov** [comment]
@edwarnicke
If we implement this, NSE labels will effectively become arrays of labels, packed into a string. It makes sense to change the API to have labels be arrays.
Do you approve such change in the API?

**Comment by edwarnicke** [comment]
@d-uzlov I don't understand why this implies labels being an array packed as a string...

**Comment by d-uzlov** [comment]
Well, if the description in this issue is correct, then "`label=one,two` should match both `label=one` and `label=two`" looks pretty much like "label should be considered an array, and `label=<value>` should match any endpoint which label contains `<value>` in it".
That is: **_if_** the description in this issue is correct. If it is not, we should probably discuss it in the parent issue.

**Comment by edwarnicke** [comment]
I think there's discussion to be had in the parent issue.

**Comment by Bolodya1997** [comment]
Don't actually needed because instead of doing this:
```
step: 1 -> step: 2
step: 3 -> step: 4

nse-1: { step: 1,3 } 
nse-2: { step: 2 }
nse-3: { step: 4 }
```
we can do that:
```
step: 1 -> step: 2
labe: a -> labe: b

nse-1: { step: 1, labe: a } 
nse-2: { step: 3 }
nse-3: { labe: b }
```
