### ISSUE TITLE
NS expire chain element logic is invalid

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#877]
## Intro
Currently NS expire implements the following logic for single NS:
```
0. start listening for NSEs updates
1. register NS
2. receive update for NSE implementing NS
   * not expired - create a timer with NSE expiration time, store it to the list
   * expired - delete NSE timer from the list
      * list is empty - delete NS
```
Every NSE implementing NS added after NS registration owns it. When last NSE owning NS is removed, NS is removed.

Common scenario for running NSEs currently is:
```
1.   start NSE
2.   register NS
3.   register NSE
4-n. refresh NSE registration
```
If there are multiple NSEs implementing same NS, (2) does nothing for all of them except first.

## Issue
If we have 2 endpoints implementing same service and one of them starts after the previous death/unregistration there can be such case:
```
1.  (NSE-1) starts
2.  (NSE-1) registers NS
3.  (NSE-1) registers NSE-1
4.  (NSE-1) dies
5.  (NSE-2) starts
6.  (NSE-2) registers NS
7.          expiration time for NSE-1
8.          NSE-1 unregisters
9.          NS unregisters
10. (NSE-2) registers NSE-2
11. (NSC)   starts
12. (NSC)   requests NS
13. (NSC)   ...
14. (NSC)   timeout for the request
```

## Problem
1. We have different entities - NS, NSE. NSE implements NS, but doesn't own it. There possibly can be a case when there is no single NSE fully implementing NS (composite NS).
2. It is OK if we have NS that is not implemented by any NSE - in some future there can possibly appear some NSE implementing this NS. For the NSC perspective both cases (NS without NSEs, no NS) are the same - request should fail on timeout with _no NS_ error.

It means that currently existing NS expire chain element is invalid.

### Don't expire NS
The one who registers NS should also unregister it. If we have not used NS's, they can be removed by NSM admin manually.

### Add expiration time for NS
Add expiration time for NS registration and use refresh logic as for NSEs. NS's added as CRDs by k8s api wouldn't be expired in such case.

**Comment by Bolodya1997** [comment]
@edwarnicke cc

**Comment by edwarnicke** [comment]
I would suggest not expiring NS's.  Most of the time it is expected that NS's will be added administratively, we add them as part of NSE registration as a courtesy... its not expected that will be the usual case.

**Comment by denis-tingaikin** [comment]
I think this problem is super actual.

I like an option to get rid of ns expire chain element. In this case for registry memory, we could add cli cmd- application that also can be useful for admins that using the floating registry.

@edwarnicke Thoughs?

**Comment by edwarnicke** [comment]
@denis-tingaikin Good idea!  Lets add it to the backlog :)
