### ISSUE TITLE
Add test of choosing endpoint created during request

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/sdk#916]
## Overview

If new endpoint was created and registered during request, and requests to old endpoints failed, then we should automatically query a request to this new endpoint.
Right now there is no test for this scenario, so a new sandbox test is needed.

## Implementation details

Test steps:
1. Create network service with 2 matches.
2. Create endpoint for second match.
3. During request to endpoint for second match spawn an endpoint for first match and return an error.
4. Check that second endpoint successfully received the request.

## References

https://github.com/networkservicemesh/sdk/issues/892

**Comment by denis-tingaikin** [comment]
Related to https://github.com/networkservicemesh/sdk/issues/892
