### ISSUE TITLE
Heal doesn't update restored endpoint name

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#918]
## Expected Behavior

If endpoint restarts, it registers with a new name. Heal should update endpoint name in the connection for such endpoint.

## Current Behavior

Heal doesn't update endpoint name and so refresh requests start failing after expire happen for the old endpoint registration.

**Comment by edwarnicke** [comment]
@Bolodya1997 Should Endpoint names be ephemeral between restarts?

**Comment by Bolodya1997** [comment]
There is a problem that we are trying to restore existing connection and it knows about the last Endpoint name. But restored endpoint doesn't and so it registers with a new name.
It actually becomes a problem when old Endpoint registration expires and there is no more Endpoint with the old name in registry, but we are keep trying to wait until it arrives (because connection is OK and no healing starts again).

I suppose that solution should be the following:
1. Endpoint has some format of name how it can be generated - e.g. (pod_name-uuid)
2. During the registration Endpoint tries to find from the NSMgr Endpoints registered with `Name: pod_name-..., URL: my-url`
3. If there is some Endpoint with such name+url, it means that Endpoint has been restarted and so it registers itself with this name.

So all of this logic should be included into the `setid` NSE registry chain element.

**Comment by edwarnicke** [comment]
OK... let me break this down to make sure I'm understanding correctly.

1. NSC1 is connected via a Path to NSE1
2. NSE1 restarts and reregisters with NSE1'

the first thing I'm confused about is: how does heal to NSE1 work at all?  NSE1' having restarted would have a completely different callback unix file socket than NSE1, and so heal should simply *fail*.

**Comment by Bolodya1997** [comment]
You are right, there is no way to restore NSE if it is connected via the unix socket. But we doesn't forbid Endpoints to be registered with the IP address, so in such case the address will be the same after the restart and we will face such problem.

**Comment by edwarnicke** [comment]
> But restored endpoint doesn't and so it registers with a new name.

Why not just have the endpoints register with their Pod name?

**Comment by Bolodya1997** [comment]
> Why not just have the endpoints register with their Pod name?

Let's continue this discussion in the PR thread - https://github.com/networkservicemesh/sdk/pull/932#issuecomment-850088506.

**Comment by Bolodya1997** [comment]
We are no more supporting restore case, so this should be closed.
