### ISSUE TITLE
Support heal for NSC

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/sdk#938]
## Problem

Currently healing is not supported for NSC. Client is created on gRPC connection and doesn't have any options to restore it. In NSMgr restore case user needs to restart NSC pod to make it work again.

## Solution

Client chain should be modified with `connect` and `heal` chain elements:
```go
additionalFunctionalityClient := ...

chain.NewNetworkServiceClient(
	updatepath.NewClient(opts.name),
	serialize.NewClient(),
	refresh.NewClient(ctx),
	metadata.NewClient(),
	additionalFunctionalityClient,
	opts.authorizeClient,
	adapters.ServerToClient(
		chain.NewNetworkServiceServer(
			clienturl.NewServer(connectTo),
			heal.NewServer(ctx),
			connect.NewServer(ctx, func(ctx context.Context, cc grpc.ClientConnInterface) {
				return chain.NewNetworkServiceClient(
					heal.NewClient(ctx, networkservice.NewMonitorConnectionClient(cc)),				
					networkservice.NewNetworkServiceClient(cc),
				)
			}, connect.WithDialOptions(dialOptions...)),
	)),
)
```

## References

client chain - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/client/client.go

**Comment by denis-tingaikin** [comment]
I think we also need to cover this scenario by tests on SDK

**Comment by Bolodya1997** [comment]
> I think we also need to cover this scenario by tests on SDK

There is a local NSMgr restore case added in https://github.com/networkservicemesh/sdk/pull/811.

**Comment by edwarnicke** [comment]
@Bolodya1997 I am really confused why we are putting an adaptation to server into client.  We have a [heal client](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/heal/client.go#L50) that is [already in the client chain](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/client/client.go#L90).

Could you help me understand?

**Comment by Bolodya1997** [comment]
> @Bolodya1997 I am really confused why we are putting an adaptation to server into client. We have a [heal client](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/heal/client.go#L50) that is [already in the client chain](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/client/client.go#L90).
> 
> Could you help me understand?

Probably _heal_ client is a bit confusing name, because it is mostly a _monitor_ client that calls _heal_ and _restore_ handles passed by the heal server through the Request context. If we want to make heal working for the hop, we need such part of chain to exist on it: `... -> heal server -> ... -> connect server -> ... -> heal client -> ...`.
1. heal server - makes active healing with retrying Requests on given chain
2. connect server - closes and creates again failed gRPC connection during the healing
3. heal client - monitors remote side and requests heal server for restore/heal

**Comment by edwarnicke** [comment]
Got it.

Question: Do we really want to put this in *every* client chain, or just the NSC client chain?

I would expect the existing healing behavior in nsmgr and forwarder to garner its behavior from their inclusion of the heal.NewServer in the Server parts of their chain.

It seems this is likely something we just want in the NSCs...

**Comment by Bolodya1997** [comment]
> Question: Do we really want to put this in _every_ client chain, or just the NSC client chain?

Right now we have the same chains both for the `NewClient` and for the `NewClientFactory`. Implementing this issue means moving old `NewClient` chain to the `NewClientFactory` and creating a new one described here for the `NewClient`.

So it is only for the NSC chain.
