### ISSUE TITLE
Add point2multipoint ipam

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/sdk#951]
## Overview
The new IPAM service chain should provide single point IPAM server chain element. There can be cases when the endpoint providing IPAM service needs only one address to be allocated.

**Comment by denis-tingaikin** [comment]
PRs are welcome! 👍

**Comment by denis-tingaikin** [comment]
@ljkiraly Is this issue actual?

**Comment by ljkiraly** [comment]
I missed to close this one, thanks for notice.
I is solved by #1093
