### ISSUE TITLE
The name of registry service is hard-coded in dnsresovle

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/sdk#969]
## Question

Can be the service name of the registry parameterized? 
Currently it is set to it's default value in sdk/pkg/registry/common/dnsresolve/const.go
const NSMRegistryService = "nsm-registry-svc"

## Examaples

Maybe some prefix can be added to a given mandatory value.
<some_name>-registry-svc

## Context

The name of the service was changed in helm and the nse can not register.

**Comment by ljkiraly** [comment]
#959 solved this issue

**Comment by ljkiraly** [comment]
Now the service name is still hard-coded, just changed to 'registry'. It is set in sdk/pkg/registry/common/dnsresolve/common.go

Is the naming fixed by intention?

**Comment by denis-tingaikin** [comment]
actually, the name can be configured via options. But, yes by default are using these constants https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/dnsresolve/options.go#L36

**Comment by denis-tingaikin** [comment]
Also note, it is only half of the DNS query. 
DNS query could be {$registryServiceName}.${cluster.domain}

**Comment by denis-tingaikin** [comment]
>Maybe some prefix can be added to a given mandatory value.
<some_name>-registry-svc

@edwarnicke What do you think about this?

**Comment by edwarnicke** [comment]
@ljkiraly - does the fact that the defaults are just constants and they can be set arbitrarily via Options solve your problem?

**Comment by ljkiraly** [comment]
Yes, it's OK now. 
I missed to set/modify NSM_REGISTRY_URL in nsmgr-proxy.yaml and nsmgr.yaml. 
Thanks for support

**Comment by edwarnicke** [comment]
@ljkiraly Delighted to help!  And thank you for your quick response on whether this meets your needs :)
